media-video/mpv/mpv-9999.ebuild

There is no such option anymore, see: https://github.com/mpv-player/mpv/commit/58ba2a9087dfa6bf6a81177c77f86e01acd33286
Current ebuild doesn't build on latest git master.
If something is wrong in my PR, consider it as bug report at least. I don't have RPi, so I'm not sure this is 100% correct patch.

media-video/mpv: Delete rpi-gles option

---

sys-apps/ed/ed-1.12.ebuild

sys-apps/ed is required to create a stage1.
Please add a keyword.
```
<snip>
[ebuild  N    ] sys-apps/ed-1.12 to /tmp/stage1root/
<snip>
The following keyword changes are necessary to proceed:
(see "package.accept_keywords" in the portage(5) man page for more details)
=sys-apps/ed-1.12 **
```

sys-apps/ed: add ~amd64-fbsd keyword

---

profiles/default/bsd/fbsd/amd64/10.1/package.use.force
profiles/default/bsd/fbsd/amd64/10.2/package.use.force

I was confirmed that this problem occurs in python 3.4.
I have changed the version specified.
FYI,
https://bugs.gentoo.org/show_bug.cgi?id=494744

profiles: FreeBSD 10.0 or later, python3 force set USE=threads on amd64-fbsd.

---

dev-python/bcrypt/bcrypt-2.0.0.ebuild
dev-python/cairocffi/cairocffi-0.5.3-r1.ebuild
dev-python/cairocffi/cairocffi-0.5.4.ebuild
dev-python/cairocffi/cairocffi-0.6-r1.ebuild
dev-python/cairocffi/cairocffi-0.6.ebuild
dev-python/cairocffi/cairocffi-0.7.1.ebuild
dev-python/cairocffi/cairocffi-0.7.2.ebuild
dev-python/cffi/cffi-0.8.6.ebuild
dev-python/cffi/cffi-1.1.2.ebuild
dev-python/cffi/cffi-1.2.1.ebuild
dev-python/cryptography/cryptography-1.0.ebuild
dev-python/xcffib/xcffib-0.1.10.ebuild
dev-python/xcffib/xcffib-0.2.0.ebuild
dev-python/xcffib/xcffib-0.2.1.ebuild
dev-python/xcffib/xcffib-0.2.5.ebuild
dev-python/xcffib/xcffib-0.3.2.ebuild
dev-python/xcffib/xcffib-0.3.4.ebuild

Cffi shouldn't be installed for PyPy, PyPy ships with a version of cffi in its core, and we shouldn't be installing a (potentially different) version of cffi over top of it. This removes pypy from PYTHON_TARGETS for dev-python/cffi and adjusts the dependencies of all PyPy-compatible packages that require cffi, both fixing the cffi use flags and, when >=cffi-1.0 is required, ensuring a new enough version of PyPy is installed.
I've also re-added the PyPy target to dev-python/cryptography, also adding the PyPy version requirement, I noticed pypy was dropped by @jlec in 86ff0808ed5b321913e4458d2fa87466bc25d11a, though he noted the version requirement.

Don't install cffi for PyPy

---

media-sound/spotify/spotify-0.9.17.1-r1.ebuild

The URL link has a 'ch-de' localization tag, which
prints messages in German.

media-sound/spotify: Fix homepage URL

---

profiles/package.mask
x11-misc/sddm/files/sddm-0.11.0-consolekit2.patch
x11-misc/sddm/files/sddm-0.11.0-upower.patch
x11-misc/sddm/sddm-0.11.0-r2.ebuild

USE=consolekit now means real consolekit2 support instead of a postinst message
ck2 patches taken from pending https://github.com/sddm/sddm/pull/438
carried over existing upower patch though not sure if still required or why it was introduced
dropped keywords as long as sys-auth/consolekit is masked

x11-misc/sddm: Add patches for consolekit2 support

---

app-emulation/virt-manager/virt-manager-9999.ebuild

New repo: https://github.com/virt-manager/virt-manager
Reference:
https://git.fedorahosted.org/cgit/virt-manager.git/commit/?id=c7c6b1e5cd2b9b918fa7b2dd3a7ed648517ba436

app-emulation/virt-manager-9999: Upstream repo moved to github.

---

profiles/arch/ia64/package.use.mask
profiles/arch/sparc/package.use.mask
sci-misc/boinc/boinc-7.4.42-r1.ebuild

This fixes bug https://bugs.gentoo.org/show_bug.cgi?id=556670. The arches ~ia64 and ~sparc were dropped, since wxGTK[webkit] is not supported on those platforms. Maybe an additional useflag should be added to boinc or the X useflag should be masked for the arches.

sci-misc/boinc: Mask USE=X on arches with unkeyworded deps, use wxGTK 3.0

---

dev-util/ninja/ninja-1.6.0.ebuild
dev-util/ninja/ninja-9999.ebuild
dev-util/re2c/re2c-0.14.3.ebuild

Packages for building >=sys-devel/llvm-3.7.0 is missing Gentoo/FreeBSD keyword.
Please add keyword.
sys-devel/llvm-3.7.0 DEPEND dev-util/ninja.
dev-util/ninja DEPEND dev-util/re2c.
```
!!! SYNC setting found in make.conf.
This setting is Deprecated and no longer used.  Please ensure your 'sync-type' and 'sync-uri' are set correctly in /etc/portage/repos.conf/gentoo.conf
These are the packages that would be merged, in order:
Calculating dependencies... done!
[ebuild  N    *] dev-util/re2c-0.14.3::gentoo  2517 KiB
[ebuild  N    *] dev-util/ninja-9999::gentoo  USE="-doc -emacs {-test} -vim-syntax -zsh-completion" 0 KiB
[ebuild     U  ] sys-devel/llvm-3.7.0-r1:0/3.7.0::gentoo [3.6.1:0/3.6::gentoo] USE="(clang) libffi ncurses python static-analyzer -debug -doc (-gold) -libedit -lldb% …
```

dev-util/re2c and dev-util/ninja: keyword request for ~amd64-fbsd, ~x86-fbsd.

---

media-video/mpv/mpv-9999.ebuild

Several flags were removed in upstream. See mpv-player/mpv@d04d238 and mpv-player/mpv@091bfa3.

media-video/mpv: Remove no longer available flags

---

dev-util/nvidia-cuda-toolkit/nvidia-cuda-toolkit-7.5.18-r1.ebuild

@jlec This extends the library path to include the NVIDIA's optimizing compiler libraries for [LLVM](https://developer.nvidia.com/cuda-llvm-compiler). For exampled needed for the arrayfire [python bindings](https://github.com/arrayfire/arrayfire-python/wiki).
I had to pass --force to repoman, since the nvidia-cuda-toolkit-6.5.19* required `>=x11-drivers/nvidia-drivers-343.22[uvm]`, which were dropped with commit cf5f43793b. Raising the dependency to 346.96 wasn't enough and now it's quite late..

dev-util/nvidia-cuda-toolkit: Add CUDA LLVM libraries to LDPATH

---

kde-apps/kde-l10n/kde-l10n-15.08.1.ebuild

Fixes https://bugs.gentoo.org/show_bug.cgi?id=561066

kde-apps/kde-l10n: Add missing DEPEND

---

kde-apps/kde-wallpapers/files/kde-wallpapers-15.08.0-kf5-port.patch
kde-apps/kde-wallpapers/kde-wallpapers-15.08.0.ebuild
kde-apps/kde-wallpapers/kde-wallpapers-15.08.1.ebuild
kde-base/kdebase-startkde/kdebase-startkde-4.11.22.ebuild

Fixes a bug and gets rid of giant kdelibs:4 dependency just to install wallpapers in kde-applications-15.08.
Prepare kde-base/kdebase-startkde for that as well.

'Port' kde-wallpapers to kf5, fix kde-base/kdebase-startkde RDEPEND

---

media-gfx/exiv2/exiv2-0.25-r1.ebuild
media-gfx/exiv2/files/exiv2-0.25-fix-without-zlib.patch

Fixed upstream in >=0.26
See also: http://dev.exiv2.org/issues/1103
Gentoo bug 1: https://bugs.gentoo.org/show_bug.cgi?id=552046
Gentoo bug 2: https://bugs.gentoo.org/show_bug.cgi?id=535836

media-gfx/exiv2: Fix header if USE=-png

---

app-arch/lzip/lzip-1.18_pre1.ebuild

https://bugs.gentoo.org/show_bug.cgi?id=502018
Test phase passed.
```
>>> Test phase: app-arch/lzip-1.18_pre1
gmake -j8   -j1 check
testing lzip-1.18-pre1...............................
tests completed successfully.
>>> Completed testing app-arch/lzip-1.18_pre1
```

app-arch/lzip: add ~amd64-fbsd keyword, bug 502018.

---

sys-apps/rng-tools/files/rng-tools-5-fix-noctty.patch
sys-apps/rng-tools/files/rngd-initd-r1-4.1
sys-apps/rng-tools/rng-tools-5-r2.ebuild

This revision patches the source file 'rngd_entsource.c', adding O_NOCTTY
flag to the open() call that opens the entropy source for rngd.

sys-apps/rng-tools: open entropy src with O_NOCTTY flag wrt bug #556456.

---

media-libs/gavl/files/1.4.0-x32.diff
media-libs/gavl/gavl-1.4.0-r1.ebuild

media-libs/gavl: Add patch for x32, bug #472288

---

sys-apps/irqbalance/files/irqbalance.service.1
sys-apps/irqbalance/irqbalance-1.0.9-r1.ebuild

This series of commits improve the sys-apps/irqbalance service unit in the following ways:
- Use `--foreground` instead of `--debug` for daemonization.  This option was added in https://github.com/Irqbalance/irqbalance/commit/827c08f289065df5db980a8c0fcd4bc31638172f waaay back in late 2011, and all versions in Gentoo that use the systemd service file support it.
- Use the file /etc/irqbalance.env as an `EnvironmentFile` if it exists, and use its `$IRQBALANCE_ARGS` variable in `ExecStart`.  This works whether the file exists or not.
- Create a revbump to sys-apps/irqbalance-1.0.9 that installs the upstream file `misc/irqbalance.env` into `/etc`.
Note that I haven't tested the revbump outside of running `ebuild install` and checking the contents of the `image/` directory. I did test the …

sys-apps/irqbalance: misc. improvements to service unit

---

app-office/libreoffice/libreoffice-4.4.9999.ebuild
app-office/libreoffice/libreoffice-5.0.9999.ebuild
app-office/libreoffice/libreoffice-9999.ebuild

based on review in https://github.com/gentoo/gentoo/pull/178, mostly done.
Warning, none of this was tested beyond "does not immediately bail out"
Not done yet:
- src_configure
- postgres check (it seems obsolete right now - no <9.0 in tree - but might become useful again)

app-office/libreoffice: Improve ebuild

---

x11-wm/enlightenment/enlightenment-0.19.12.ebuild

\>=dev-libs/efl-1.15.2
All previous versions are blacklisted in configure
\>=media-libs/elementary-1.15
Fixes build failure

x11-wm/enlightenment: DEPEND on >=dev-libs/efl-1.15.2

---

dev-qt/qtchooser/qtchooser-0_p20150102.ebuild

https://bugs.gentoo.org/show_bug.cgi?id=529196
Test phase passed.
https://bugs.gentoo.org/show_bug.cgi?id=529196#c20

dev-qt/qtchooser: add ~x86-fbsd keywords, bug 529196.

---

dev-libs/openspecfun/openspecfun-0.4-r1.ebuild

Right now, building `dev-libs/openspecfun-0.4-r1` on a prefix system fails because of QA violations: the `DESTDIR` set falls outside the prefix.
This can easily be fixed by referencing `${ED}` instead of `${D}` as `DESTDIR` in the `emake` call.

dev-libs/openspecfun: Respect ${EPREFIX}

---

eclass/autotools.eclass

gettext 0.19.6 supports AM_GNU_GETTEXT_REQUIRE_VERSION in addition to
AM_GNU_GETTEXT_VERSION.

autotools.eclass: support AM_GNU_GETTEXT_REQUIRE_VERSION

---

net-libs/nodejs/nodejs-4.1.1.ebuild

In the current ebuild, nodejs linking will `-fuse-gold` instead of the system `ld` on 64 bit Linux.
This creates problems for prefix, when the flag is set and nodejs-bundled gold tries to link incompatible host libraries instead of prefix libraries.
Even if this does not cause problems for a normal Gentoo installation, the application should respect the linker that is set by the system and not override it.
(pinging @jlec, but this is a minor modification so I don't know if you've got comments for that)

net-libs/nodejs: respect system ld, binutils

---

net-misc/asterisk/asterisk-11.19.0-r2.ebuild
net-misc/asterisk/asterisk-13.5.0-r2.ebuild

net-dialup/radiusclient-ng is no longer maintained upstream. It was
superseded by net-dialup/freeradius-client
Gentoo-Bug: 563410

net-misc/asterisk: use freeradius-client instead of radiusclient-ng

---

mail-mta/netqmail/files/use-new-path-for-functions.sh.patch
mail-mta/netqmail/netqmail-1.06-r4.ebuild

@mgorny 
https://bugs.gentoo.org/show_bug.cgi?id=504116
https://bugs.gentoo.org/show_bug.cgi?id=504392

mail-mta/netqmail: Update mkservercert to use new path for functions.sh

---

dev-perl/Exporter-Tiny/Exporter-Tiny-0.42.0.ebuild
dev-perl/List-MoreUtils/List-MoreUtils-0.413.0.ebuild
virtual/perl-File-Path/perl-File-Path-2.90.0-r3.ebuild
virtual/perl-XSLoader/perl-XSLoader-0.200.0.ebuild

KEYWORDREQ Bug,
https://bugs.gentoo.org/show_bug.cgi?id=543632
Additional Information
```
emerge -pv dev-perl/Exporter-Tiny dev-perl/List-MoreUtils
=virtual/perl-XSLoader-0.200.0 **
=virtual/perl-File-Path-2.90.0-r3 **
```
```
>>> Test phase: dev-perl/List-MoreUtils-0.413.0
* Test::Harness Jobs=8
gmake -j8 test TEST_VERBOSE=0
Running Mkbootstrap for List::MoreUtils ()
chmod 644 "MoreUtils.bs"
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/pureperl/*.t t/xs/*.t xt/*.t
t/pureperl/ab.t ......... ok
t/pureperl/Import.t ..... ok
t/pureperl/XS.t ......... ok
t/xs/ab.t ............... ok
t/xs/XS.t ............... ok
t/xs/Import.t ........... ok
t/xs/Functions.t ........ ok …
```

dev-perl/{List-MoreUtils,Exporter-Tiny} and deps: add fbsd keywords, bug 543632

---

media-sound/qtractor/qtractor-0.7.0.ebuild
media-sound/qtractor/qtractor-0.7.1.ebuild

without it qtractor fails to compile with USE=qt5 with the error:
Project ERROR: Unknown module(s) in QT: x11extras

media-sound/qtractor: add dev-qt/qtx11extras as a dependency

---

sys-apps/systemd/files/228-noclean-tmp.patch
sys-apps/systemd/systemd-9999.ebuild

From `sys-apps/systemd-228` on, many `tmpfiles.d` definitions were
switched from `v` (subvolume) to `q` (subvolume with quota).

sys-apps/systemd: Update `noclean-tmp` patch

---

app-emacs/org-mode/org-mode-8.3.2-r1.ebuild

Org mode has a long list of optional run-time dependencies.  Expend a
reasonable amount of effort to inform users of these with the help of the
readme.gentoo eclass.
This obsoletes PR #207.

app-emacs/org-mode: inform users of run-time deps

---

dev-qt/qtscript/files/4.8.6-javascriptcore-x32.patch
dev-qt/qtscript/qtscript-4.8.6-r2.ebuild
dev-qt/qtscript/qtscript-4.8.7.ebuild

No revbump because the build failed in the only cases this patch matters (x32 target).

dev-qt/qtscript: Restore x32 compatibility patch

---

dev-db/postgresql/files/postgresql.service
dev-db/postgresql/files/postgresql.tmpfilesd
dev-db/postgresql/postgresql-9.0.23-r1.ebuild
dev-db/postgresql/postgresql-9.1.19-r1.ebuild
dev-db/postgresql/postgresql-9.2.14-r1.ebuild
dev-db/postgresql/postgresql-9.3.10-r1.ebuild
dev-db/postgresql/postgresql-9.4.5-r1.ebuild
dev-db/postgresql/postgresql-9.5_beta1-r1.ebuild
dev-db/postgresql/postgresql-9999.ebuild

Instead of using a separate `tmpfiles.d` definition to create
`/run/postgresql`, let the service unit take care of it on its
own. This prevents situations where the postgresql service can't
start because `systemd-tmpfiles` wasn't run yet.
Fixes bug #563122

dev-db/postgresql: Handle RuntimeDirectory in systemd unit

---

www-servers/tomcat/files/tomcat-instance-manager-r2.bash
www-servers/tomcat/tomcat-8.0.28-r1.ebuild

This bump tweaks the behavior of test_can_deploy(), so that
it does not fail if a target directory exists AND is empty.
This can be extremely useful if the target directories are
mount points, which is very common for e.g. docker setups.
@chewi @monsieurp 
the diff of the script is here:
```diff
--- a/www-servers/tomcat/files/tomcat-instance-manager-r1.bash
+++ b/www-servers/tomcat/files/tomcat-instance-manager-r2.bash
@@ -1,11 +1,38 @@
#!/bin/bash
-# Copyright 1999-2014 Gentoo Foundation
+# Copyright 1999-2015 Gentoo Foundation
die() {
echo "${@}"
exit 1
+}
+
+dir_is_empty() {
+	# usage:
+	#  dir_is_empty <some-dir>
+	#
+	# returns 2 if the dir does not even exist
+	# returns 1 if the dir is not empty
+	# returns 0 (success) if the dir exists and is empty
+
+	local dir=$1
+	local files
+ …
```

www-servers/tomcat: revbump on tomcat-instance-manager script

---

sys-block/open-iscsi/open-iscsi-2.0.873.ebuild

More info on bugzilla: [#563082](https://bugs.gentoo.org/show_bug.cgi?id=563082).

sys-block/open-iscsi: Remove unnecessary dependency on udev (bug #563082)

---

media-libs/libwmf/files/libwmf-0.2.8.4-CVE-2015-0848+CVE-2015-4588.patch
media-libs/libwmf/files/libwmf-0.2.8.4-CVE-2015-4695.patch
media-libs/libwmf/files/libwmf-0.2.8.4-CVE-2015-4696.patch
media-libs/libwmf/libwmf-0.2.8.4-r6.ebuild

Fixed security issues:
CVE-2015-0848: heap overflow when decoding BMP images
CVE-2015-4695: heap buffer overread in meta.h
CVE-2015-4696: use-after-free flaw in meta.h
CVE-2015-4588: heap overflow within the RLE decoding of embedded BMP images
Gentoo bug:
https://bugs.gentoo.org/show_bug.cgi?id=548742
Patches imported from fedora:
http://pkgs.fedoraproject.org/cgit/libwmf.git/tree/

media-libs/libwmf: revbump with security fixes

---

media-sound/audacity/audacity-2.0.5-r1.ebuild

Starting with audacity 2.0.3, only *one* resampling library can be enabled at a
time.  Due to this, the way the USE flags are currently handled make it
impossible to use the libsoxr library.  This commit does two things to remedy
this:
- never enable libresample (which isn't recommended anymore), and
- make the libsamplerate and libsoxr USE flags exclusive, reflecting the way
the build system works.
These two minimal changes make it possible to properly select between the two
recommended resampling libraries.
Gentoo-bug: 536208
Signed-off-by: Marc Joliet <marcec@gmx.de>
[I'm not *entirely* sure if this PR is appropriate.  Audacity-2.1.1 seems to only use libsoxr now, but it's been hard masked since July and it might be good to also have a fixed version of 2.0.5.]

media-sound/audacity: fix libsamplerate/libsox dep

---

net-misc/openssh/openssh-7.1_p1-r2.ebuild

Fixed in upstream.
I think it's no longer necessary.
FYI,
https://github.com/openssh/openssh-portable/commit/398c0ffe0ec149f0d12f23c158879712b5431af4
https://github.com/openssh/openssh-portable/commit/a2438bbd28eb35a8968d193ac89b30a90e96f719

net-misc/openssh: Please drop special settings for Gentoo/FreeBSD 9.0 or later.

---

sys-boot/systemrescuecd-x86-grub/files/systemrescuecd.default
sys-boot/systemrescuecd-x86-grub/files/systemrescuecd.grub
sys-boot/systemrescuecd-x86-grub/metadata.xml
sys-boot/systemrescuecd-x86-grub/systemrescuecd-x86-grub-0.1.ebuild

Hi,
this PR will add the boot entries in grub for the SystemRescueCD, after the user will update the file grub.cfg via command-line. It will also give the user the ability to add custom boot options. The entries for the custom boot options will only be added to grub.cfg, if SRCD_BOOTOPTIONS in /etc/default/systemrescuecd is not empty.

sys-boot/systemrescuecd-x86-grub: create grub menu entries for systemrescuecd-x86

---

sys-apps/systemd/systemd-9999.ebuild

@floppym a newer lz4 version is required by `sys-apps/systemd-9999` to build. This PR depends on #220 to be merged.

sys-apps/systemd: bump required app-arch/lz4 version to 0_p131

---

media-sound/lilypond/files/lilypond-2.18.2-fontforge.patch
media-sound/lilypond/lilypond-2.18.2.ebuild
media-sound/lilypond/metadata.xml

media-sound/lilypond: fix compilation with fontforge wrt #557160

---

net-libs/http-parser/http-parser-2.6.0.ebuild

Build fails on prefix because `/usr/{bin,lib}` is outside `${EPREFIX}`.
Older version of `http-parser` work fine.

net-libs/http-parser: respect ${EPREFIX}

---

media-sound/audacity/metadata.xml

As per the comments in https://github.com/gentoo/gentoo/pull/292 I have updated the `libsoxr` USE flag description as well as added a local one for `libsamplerate`.

media-sound/audacity: update/add samplerate converter USE flag descriptions

---

media-sound/lilypond/lilypond-2.18.2-r1.ebuild
media-sound/lilypond/lilypond-2.18.2.ebuild

I did a few minor improvements that I thought were good. If you wonder why I am only fixing version 2.18.2, it is because I plan to just copy changes to the live ebuild and then bump the 2.19 version in one go to save me some work.
Also I revbumped on each dependency change and to satisfy repoman I had to drop to ~arch so these ebuilds will have to be stabilized eventually (before bumping 2.19).
@idella 
Also, could you confirm bug #558544 [1] (and maybe also get someone to CC arch teams, hopefully)? It annoys me that stable lilypond pulls in unstable metapost.
[1] https://bugs.gentoo.org/show_bug.cgi?id=558544

media-sound/lilypond: small improvements and fix bug #557320

---

app-text/asciidoc/asciidoc-8.6.9-r1.ebuild
app-text/asciidoc/asciidoc-8.6.9-r2.ebuild
app-text/asciidoc/asciidoc-9999.ebuild
app-text/asciidoc/metadata.xml

(This is a continuation of PR #291, which is thus obsolete.)
This small patch series attempts to fix some dependency issues with app-text/asciidoc, as detailed in bug #366763. It revbumps app-text/asciidoc to add a dependency on dblatex and on www-client/w3m or www-client/lynx, one of which is needed for the text output of a2x to work (i.e., `a2x -f text`).  I will probably add app-text/highlight as another alternative to dev-python/pygments after I've tested it.
Furthermore, I have added myself as proxy-maintainer at the suggestion of @djc and removed him as maintainer.

Fix asciidoc deps

---

app-text/asciidoc/asciidoc-8.6.9-r2.ebuild
app-text/asciidoc/asciidoc-9999.ebuild

Use readme.gentoo to refer to the a2x(1) man page for a list of runtime
dependencies instead of forcing the app-text/dblatex and lynx/w3m dependencies.
Since this commit removes the direct dependency on app-text/dblatex, it also
restores KEYWORDS to its previous state.
Gentoo-bug: 565844
Signed-off-by: Marc Joliet <marcec@gmx.de>

app-text/asciidoc: use readme.gentoo for some deps

---

dev-libs/libindicator/libindicator-12.10.1-r301.ebuild

Patches should reference upstream bug reports so people can quickly
find discussion on a particular issue.
Package-Manager: portage-2.2.24

dev-libs/libindicator: Reference upstream bug report for patch

---

sys-apps/shadow/files/shadow-4.2.1-verbose-error-when-uid-doesnt-match.patch
sys-apps/shadow/shadow-4.2.1-r2.ebuild

Everything is explained in the patch file by Hank Leininger:
> Currently the error is just:
> 
> newuidmap: Target [pid] is owned by a different user
> 
> With this patch it will be like:
> 
> newuidmap: Target [pid] is owned by a different user: uid:0 pw_uid:0 st_uid:0, gid:0 pw_gid:0 st_gid:99
> 
> Why is this useful?  Well, in my case...
> 
> The grsecurity kernel-hardening patch includes an option to make parts
> of /proc unreadable, such as /proc/pid/ dirs for processes not owned by
> the current uid.  This comes with an option to make /proc/pid/
> directories readable by a specific gid; sysadmins and the like are then
> put into that group so they can see a full 'ps'.
> 
> This means that the check in new[ug]idmap fails, as in the above quoted
> error - /proc/[targetpid] is owned by …

sys-apps/shadow: Patch new[ug]idmap to print verbose err on ownership mismatch

---

app-text/asciidoc/asciidoc-8.6.9-r2.ebuild
app-text/asciidoc/asciidoc-9999.ebuild

The vim-syntax USE flag is useless now, for the following reasons:
- The actions it controls have no effect, since the Makefile.in doesn't do
anything vim-related anymore, as mentioned in the CHANGELOG.
- Vim comes with its own syntax file since version 7.4, which is maintained (by
AsciiDoc upstream, according to its header) and was last updated in 2014,
whereas the upstream syntax file has not been changed since 2013.
Gentoo-bug: 530808
Signed-off-by: Marc Joliet <marcec@gmx.de>

app-text/asciidoc: remove vim-syntax from IUSE

---

app-text/asciidoc/asciidoc-8.6.9-r2.ebuild

Docompress should only be called when USE=examples.
Gentoo-bug: 555400
Signed-off-by: Marc Joliet <marcec@gmx.de>

app-text/asciidoc-8.6.9-r2: fix docompress call

---

app-text/linuxdoc-tools/linuxdoc-tools-0.9.71-r1.ebuild

Inherit latex-package eclass and rehash kpathsea database after
installation and removal. Make TeX styles installation path consistent
with latex-package eclass.

app-text/linuxdoc-tools: fix TeX styles installation, minor cleanups

---

net-firewall/fwknop/fwknop-2.6.7-r1.ebuild
net-firewall/fwknop/fwknop-2.6.7-r2.ebuild

As cipherdyne.org tends to be down sometimes.

net-firewall/fwknop: add GitHub repo to HOMEPAGE

---

app-crypt/yubikey-neo-manager/yubikey-neo-manager-1.1.0-r1.ebuild
app-crypt/yubikey-neo-manager/yubikey-neo-manager-1.2.1-r1.ebuild
app-crypt/yubikey-neo-manager/yubikey-neo-manager-1.3.0-r1.ebuild

This package has a runtime dependency to pycrypto. Without that, it
fails with the following error:
Traceback (most recent call last):
File "/usr/lib/python-exec/python2.7/neoman", line 3, in <module>
from neoman import main
File "/usr/lib64/python2.7/site-packages/neoman/main.py", line 33, in <module>
from neoman.view.main import MainWindow
File "/usr/lib64/python2.7/site-packages/neoman/view/main.py", line 30, in <module>
from neoman.model.applet import Applet
File "/usr/lib64/python2.7/site-packages/neoman/model/applet.py", line 29, in <module>
from Crypto.Signature import PKCS1_PSS
ImportError: No module named Crypto.Signature

app-crypt/yubikey-neo-manager: add dev-python/pycrypto to RDEPEND

---

dev-util/weka/metadata.xml
dev-util/weka/weka-3.6.12-r1.ebuild
dev-util/weka/weka-3.6.6-r2.ebuild

Weka only ships a wrapper class for the actual libsvm package. Add a use
flag named "svm" and pull in sci-libs/libsvm[java] for proper SVM support
when the use flag is enabled.
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=565550
Upstream-URL: https://weka.wikispaces.com/LibSVM

dev-util/weka: add missing rdep on libsvm and the use flag "svm" #565550

---

dev-libs/libaio/files/libaio-0.3.110-link-stdlib.patch
dev-libs/libaio/libaio-0.3.110.ebuild

When '-fstack-protector-strong' is included in CFLAGS, the function
'__stack_chk_fail_local' needs to be pulled from libc. However, upstream
uses -nostdlib to avoid linking against any C library or gcc libs. Link
against '-lc' and '-lgcc' to pull in the required symbols. Also pass
'-Wl,--as-needed' so the fuctions are pulled from the internal
libc_nonshared.a instead of linking against the shared library.
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=558406
Debian-Bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764509

dev-libs/libaio: link against -lc to pull the fortified functions #558406

---

app-shells/autojump/autojump-22.2.4-r4.ebuild
app-shells/autojump/files/autojump-22.4.4-fix-__aj_error-typo.patch
app-shells/autojump/files/autojump-22.4.4-fix-autojump.fish-bugs.patch
app-shells/autojump/metadata.xml

This goal of this PR is to add FISH support.  This is done in the first commit, which required including two upstream patches (they can be removed with the next version bump, though).  The other three commits are pretty much just clean ups that I made while working on FISH support, so decided to include them here.
Note that I made FISH support unconditional, since zsh support is also unconditional, and it only installs a single file.
I'm not sure if the second patch is really required, but it seems like a good idea to me.  IIUIC, it will limit the autojump script to the python implementations listed in `PYTHON_COMPAT`, that is, it will cause the script to fail for unsupported Python implementations.
For easier comparison, here's a diff of the ebuild revisions:
% git diff master.. -C -C …

app-shells/autojump: add FISH support, misc. clean ups

---

sys-devel/llvm/llvm-9999.ebuild

As part of 3.7.* releases, LLVM has officially added support for the
BPF backend. This backend emits instructions in the eBPF language,
that is used in the homonymous Linux kernel virtual machine. Users of
LLVM can write a program in C and have it compiled directly into BPF.
More info available in the commit that introduced the backend:
https://github.com/llvm-mirror/llvm/commit/4fe85c75482f9d11c5a1f92a1863ce30afad8d0d
This commit adds support for compiling this backend conditionally, if
the 'bpf' USE flag is enabled. Although one could use the
'multitarget' USE flag to generate all targets, it would come at the
cost of significantly increased compilation time.

sys-devel/llvm: add BPF backend to compiled targets

---

sys-fs/cryptsetup/cryptsetup-1.6.5.ebuild

cryptsetup-1.6.5 has an incorrect link to cryptsetup wiki because
upstream has migrated to gitlab.

sys-fs/cryptsetup: fix obsolete wiki URL #551994

---

media-video/aegisub/aegisub-3.2.2.ebuild
media-video/aegisub/aegisub-9999.ebuild
media-video/aegisub/files/aegisub-3.2.2-add-missing-pthread-flags.patch
media-video/aegisub/files/aegisub-9999-add-missing-pthread-flags.patch

This also fixes build with GCC-5.
Gentoo-Bug: 568878

media-video/aegisub: add missing pthread flags

---

media-video/aegisub/aegisub-3.2.2.ebuild
media-video/aegisub/aegisub-9999.ebuild

dev-lang/luajit does not have sub-slots and we require SLOT 2 only.
Package-Manager: portage-2.2.24

media-video/aegisub: drop useless slot operator on luajit dependency

---

dev-php/pecl-xdiff/metadata.xml
dev-php/pecl-xdiff/pecl-xdiff-1.5.2-r2.ebuild

Upstream development has moved to github (away from
svn.php.net),
Also bumped EAPI to v5 to appease repoman.
Package-Manager: portage-2.2.24

dev-php/pecl-xdiff: Add upstream metadata

---

dev-libs/glib/glib-1.2.10-r6.ebuild
net-wireless/spectools/spectools-2011.08.1_p20140618-r1.ebuild
sci-biology/embassy-vienna/embassy-vienna-1.7.2.650.ebuild
x11-libs/gtk+/gtk+-1.2.10-r13.ebuild

I've fixed a number of ebuilds that implicitly assumed -std=gnu89 and failed with missing symbols with GCC 5 changing the default C standard.

Fix packages broken by GCC 5 moving from -std=gnu89 to -std=gnu11 by default

---

eclass/virtualx.eclass

https://bugs.gentoo.org/show_bug.cgi?id=569876

virtualx.eclass: fix diagnostic messages in virtx()

---

net-analyzer/zabbix/zabbix-2.2.11.ebuild
net-analyzer/zabbix/zabbix-2.2.5.ebuild
net-analyzer/zabbix/zabbix-2.2.9.ebuild
net-analyzer/zabbix/zabbix-2.4.5.ebuild
net-analyzer/zabbix/zabbix-2.4.7.ebuild

I've delete the reference to the old `files/1.6.6/postinstall-en.txt` file.
The `files/1.6.6/postinstall-en.txt` has been removed on the 178b4659cf9e6b59383077fc6cddf905de620fef .
----
I've encountered:
```
>>> Failed to emerge net-analyzer/zabbix-2.2.5, Log file:
>>>  '/var/tmp/portage/net-analyzer/zabbix-2.2.5/temp/build.log'
* Messages for package net-analyzer/zabbix-2.2.5:
* ebuild fault: file '/usr/portage/net-analyzer/zabbix/files/1.6.6/postinstall-en.txt' not found
* Please report this as a bug at https://bugs.gentoo.org/
* ERROR: net-analyzer/zabbix-2.2.5::gentoo failed (install phase):
*   ebuild fault: file '/usr/portage/net-analyzer/zabbix/files/1.6.6/postinstall-en.txt' not found
* 
* Call stack:
*     ebuild.sh, line   90:  Called src_install
*   environment, line 5564: …
```

net-analyzer/zabbix: Fix ebuild fault: file 'postinstall-en.txt' not found

---

sci-biology/dialign-tx/dialign-tx-1.0.2-r1.ebuild
sci-biology/dialign-tx/files/dialign-tx-1.0.2-modernize.patch

sci-biology/dialign-tx: fixes GCC-5 inline semantics and -Wformat= warnings, #570252

---

media-sound/teamspeak-client-bin/teamspeak-client-bin-3.0.18.2.ebuild

Permission for direct download of teamspeak software from teamspeak
mirrors has been granted for Gentoo Linux. Fetch restrict is gone
but we now need to restrict mirroring. Details of this special
permission are discussed in the Gentoo Bugzilla.
Permission email: https://bugs.gentoo.org/attachment.cgi?id=421386
Gentoo-Bug: 562532
Package-Manager: portage-2.2.20

media-sound/teamspeak-client-bin: fetch restrict removed

---

media-video/mpv/mpv-9999.ebuild

Zsh completion is a separate feature from CLI player.
Thus it should be controlled by a separate 'zsh-completion' USE.
Make 'zsh-completion' USE require 'cli' USE, since completions
for a shared library are not useful.
Package-Manager: portage-2.2.24

media-video/mpv: add missing zsh-completion USE flag

---

app-crypt/libu2f-host/libu2f-host-1.0.0-r1.ebuild

This ebuild installs a udev rule that creates matching hidraw nodes
with the group 'plugdev' for non-systemd configurations. However, it
does not create the group if it doesn't exist, causing attached
devices to fail permission checks.
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=564748

app-crypt/libu2f-host: create the group 'plugdev' if necessary #564748

---

eclass/kde4-meta.eclass

Since add_kdeapps_dep would otherwise set the min version to 4.14.3
which breaks 4.4.2015.06 with USE=kontact
@gentoo/kde

kde4-meta.eclass: Depend on same version of kontact

---

media-sound/mpd/mpd-0.19.11.ebuild

This allows a user to run mpd through systemd locally, instead of a system-wide global instance under the mpd user.
Note that I am not entirely sure this (ie. copying the existing system unit as a user unit) is a correct approach, but it works without complaints here and is basically what they are doing in arch: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/mpd#n52
This probably warrants a version bump, which I can do and just omitted it for now for clarity.

media-sound/mpd: add a systemd user service

---

profiles/arch/alpha/package.use.mask
profiles/arch/alpha/package.use.stable.mask
profiles/arch/arm/package.use.mask
profiles/arch/arm/package.use.stable.mask
profiles/arch/powerpc/package.use.mask
profiles/arch/powerpc/ppc32/package.use.mask
profiles/arch/powerpc/ppc64/package.use.stable.mask

The idea is to mask sdl and rubberband USEs for the currently stable mpv version only, as opposed to all stable versions now. Since the introduction of the original USE masks, libsdl2 was stabilized and rubberband was keyworded and is currently being stabilized. I'd like to have these features available in the next stable release of mpv. Thus masks need to be adjusted for proper arch testing during the upcoming stabilization procedure.
@idella, please review and merge.
Since I've put Ian's name in the commits I expect this PR to be handled by him personally.

media-video/mpv: prepare sdl and rubberband for the next stable mpv version

---

sci-libs/scikits_learn/scikits_learn-0.14.1.ebuild
sci-libs/scikits_learn/scikits_learn-0.15.1.ebuild
sci-libs/scikits_learn/scikits_learn-0.15.2.ebuild
sci-libs/scikits_learn/scikits_learn-0.16.1.ebuild
sci-libs/scikits_learn/scikits_learn-0.17.ebuild

@jlec as discussed in IRC, scikit_learn is build against blas/cblas. Thus the dependencies should be added. I further added some missing dies.

sci-libs/scikits_learn: Missing dependencies + dies

---

net-nntp/nzbget/files/nzbget.initd

@swegener Since you're also working on merging a bump for nzbget, I thought it might be nice to improve the init script as well. All the fixes here were mentioned in https://bugs.gentoo.org/show_bug.cgi?id=550600
I simply added `--` before `${NZBGET_OPTS}`

net-nntp/nzbget: improve init script #550600

---

net-nntp/nzbget/files/nzbget.initd

Adds a missing `--` which https://github.com/gentoo/gentoo/pull/611 was missing

net-nntp/nzbget: fix init script

---

media-libs/oyranos/oyranos-9999.ebuild

Qt4 and Qt5 can now be built in one go.

media-libs/oyranos: Add USE=scanner, missing DEPENDs

---

media-video/qgifer/metadata.xml
media-video/qgifer/qgifer-0.2.1-r2.ebuild

I've fixed dependency to be from specific slot rather than version number. Seems to be more gentoo way.
Just fixing my commit issue from bugzilla by Amadeusz Żołnowski

media-video/qgifer: opencv3 slot depedency

---

media-video/aegisub/aegisub-9999.ebuild

I am currently working with upstream towards fixing all those problems we patch away in Gentoo. More fixes for 9999 to come. 3.2.2 will receive a revbump when we are done.

media-video/aegisub: adjust luajit dependency, drop unneeded patch

---

media-video/mpv/mpv-0.14.0-r1.ebuild
media-video/mpv/mpv-9999.ebuild

Upstream provides very unclear license information
about the code hidden under --enable-gpl3 switch.
See Gentoo bug 571728 for more info.
This code is disabled by default, so there is no actual change in the
build. But since we have a report in Gentoo bugzilla, add a reference to
it.
Gentoo-Bug: 571278

media-video/mpv: explicitly disable code with unclear license

---

app-text/zathura/files/zathura-9999-synctex.patch

app-text/zathura-9999 fail to build because of missing synctex patch, copying the one from 0.3.4 seems to works.
On a side note, synctex require `app-text/texlive-core-2015`, not simply `app-text/texlive-core`, otherwise, there is some missing pkg-config files.

app-text/zathura: add synctex patch for 9999

---

media-video/mpv/files/mpv-0.15.0-fix-vaapi-build-on-older-ffmpeg.patch
media-video/mpv/mpv-0.15.0-r1.ebuild

Upstream issue: https://github.com/mpv-player/mpv/issues/2737
Gentoo-Bug: 572386

media-video/mpv: fix 0.15.0 build with vaapi USE wrt bug 572386

---

net-p2p/amule/amule-2.3.1-r1.ebuild
net-p2p/amule/files/amuled.initd
net-p2p/amule/files/amuleweb.initd

Changes:
- port to EAPI=5
- remove unused flag-o-matic inherit
- add dependency on sys-libs/binutils-libs
```
--- amule-2.3.1.ebuild	2015-08-16 00:39:49.148676544 +0300
+++ amule-2.3.1-r1.ebuild	2015-10-26 22:48:04.418342061 +0300
@@ -2,9 +2,9 @@
-EAPI="2"
+EAPI=5
-inherit eutils flag-o-matic wxwidgets user
+inherit eutils wxwidgets user
MY_P=${PN/m/M}-${PV}
S="${WORKDIR}"/${MY_P}
@@ -15,16 +15,17 @@
LICENSE="GPL-2"
SLOT="0"
-KEYWORDS="alpha amd64 ppc ppc64 ~sparc x86"
+KEYWORDS="~alpha ~amd64 ~ppc ~ppc64 ~sparc ~x86"
IUSE="daemon debug geoip nls remote stats unicode upnp +X"
DEPEND=">=dev-libs/crypto++-5
>=sys-libs/zlib-1.2.1
-	stats? ( >=media-libs/gd-2.0.26[jpeg] )
+	sys-libs/binutils-libs:0=
+	stats? ( >=media-libs/gd-2.0.26:=[jpeg] )
geoip? ( dev-libs/geoip )
upnp? ( …
```

net-p2p/amule: various fixes

---

dev-ml/dose3/dose3-4.2.ebuild

Minimal adjustment for dev-ml/dose3-4.2. Trying to build against dev-ml/extlib-1.6.1 results in
```
>>> Emerging (1 of 1) dev-ml/dose3-4.2::gentoo
* dose3-4.2.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                                                [ ok ]
>>> Unpacking source...
>>> Unpacking dose3-4.2.tar.gz to /tmp/portage/dev-ml/dose3-4.2/work
>>> Source unpacked in /tmp/portage/dev-ml/dose3-4.2/work
>>> Preparing source in /tmp/portage/dev-ml/dose3-4.2/work/dose3-4.2 ...
>>> Source prepared.
>>> Configuring source in /tmp/portage/dev-ml/dose3-4.2/work/dose3-4.2 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu …
```

dev-ml/dose3: adjust extlib-dependency for dose-4.2

---

net-irc/inspircd/files/inspircd-2.0.20-deprecated-tmpnam-560362.patch
net-irc/inspircd/inspircd-2.0.20.ebuild

POSIX::tmpnam() was deprecated in Perl 5.22 which causes a failure in
./configure with various combinations of USE flags enabled on systems
with 5.22 installed.

net-irc/inspircd: patch tmpnam call (bug #560362)

---

dev-python/tempita/tempita-0.5.3-r1.ebuild

@idella Just bumped the existing ebuild and marked all arches as unstable.

dev-python/tempita: add Python 3.5 support

---

net-fs/davfs2/metadata.xml

The GLEP 67 conversion forgot to indent the maintainer tag when it converted
the herd proxy-maint to a project.

net-fs/davfs2: add the missing indentation introduced by the glep67 conversion

---

dev-dotnet/libgdiplus/libgdiplus-4.2-r1.ebuild

This fixes the issue raised by @aleclearmind [here](https://bugs.gentoo.org/show_bug.cgi?id=432224#c20), sorry about the mess.

dev-dotnet/libgdiplus: fix incorrect logic with USE=cairo

---

app-shells/bash-completion/bash-completion-2.1-r94.ebuild
app-shells/bash-completion/bash-completion-2.1_p20141224-r1.ebuild

@monsieurp
The patch was added for 2.1-r94 in fab2a7c5536a218bd909b2c7265e9c69296316dc but not for the most recent version
RepoMan-Options: --force

app-shells/bash-completion: add patch to fix bug 543100

---

net-analyzer/fail2ban/fail2ban-0.9.3-r1.ebuild

@vapier
The tests fail (like they do with 3.4) but the client and the server work well.

net-analyzer/fail2ban: add support for Python 3.5, fix fbsd  deps

---

sys-freebsd/freebsd-libexec/freebsd-libexec-10.2.ebuild

Details, please see Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=573358

sys-freebsd/freebsd-libexec: Add a workaround for gcc-5.0 or later.

---

dev-python/pyenchant/pyenchant-1.6.6.ebuild

Tests pass under py27, 34 and 35.
```diff
--- pyenchant-1.6.6.ebuild      2016-01-29 15:54:11.715155164 +0100
+++ pyenchant-1.6.6-r1.ebuild   2016-01-29 15:54:58.243701180 +0100
@@ -1,10 +1,10 @@
-# Copyright 1999-2015 Gentoo Foundation
+# Copyright 1999-2016 Gentoo Foundation
EAPI=5
-PYTHON_COMPAT=( python{2_7,3_3,3_4} pypy )
+PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} pypy )
inherit distutils-r1
@@ -14,8 +14,7 @@
LICENSE="LGPL-2.1"
SLOT="0"
-KEYWORDS="amd64 hppa ppc ppc64 sparc x86"
-IUSE=""
+KEYWORDS="~amd64 ~hppa ~ppc ~ppc64 ~sparc ~x86"
DEPEND="
>=app-text/enchant-${PV%.*}
```

dev-python/pyenchant: add support for Python 3.5

---

net-p2p/torrentinfo/torrentinfo-1.8.6.ebuild

@idella 
The tests still fail but I found the fix and made a PR upstream: https://github.com/Fuuzetsu/torrentinfo/pull/16

net-p2p/torrentinfo: add Python 3.5

---

profiles/releases/freebsd-8.2/package.mask
profiles/releases/freebsd-9.1/package.mask
sys-devel/gcc/gcc-5.3.0.ebuild

I was confirmed that emerge -e world --exclude sys-apps/portage 
using gcc-5.3.0 successfully completed.
Please add a keyword.
Tested on amd64-fbsd/10.2, amd64-fbsd/10.2/clang, x86-fbsd/10.2
Note
Since the 8.2 and 9.1 are very old, I was mask gcc-5 or later.

sys-devel/gcc: Added ~amd64-fbsd ~x86-fbsd keyword.

---

dev-python/blessings/blessings-1.6.ebuild

@idella 
Fixed tests since they need an interactive shell, see https://github.com/erikrose/blessings/issues/117
The tests pass with Python 2.7, 3.4 and 3.5.

dev-python/blessings: add py3.5, fix tests

---

net-libs/librsync/files/librsync-2.0.0-search.patch
net-libs/librsync/librsync-0.9.7-r3.ebuild
net-libs/librsync/librsync-2.0.0-r1.ebuild
net-libs/librsync/librsync-2.0.0.ebuild

I added subslots for both versions to allow automatic recompilation of dependent packages and I also put the upstream patch[¹] to fix bug #573144.
[¹] https://github.com/librsync/librsync/issues/50

net-libs/librsync: add subslots and fix bug #573144

---

media-video/mpv/mpv-0.14.0-r1.ebuild

This is the backport of 8d842d6 to 0.14.0-r1 ebuild.
The resulting installed image isn't changed, thus no revbump.

media-video/mpv: omit unneeded etc/* entries from DOCS array in 0.14.0-r1

---

dev-python/pysrt/metadata.xml
dev-python/pysrt/pysrt-1.0.1.ebuild
dev-python/pysrt/pysrt-9999.ebuild

This adds support for Python 3.5 (tests pass). It fetches from github since pypi's releases don't include tests.
I believe @Nikoli is AWOL so I am taking this package. The pull request probably won't be merged for a few days so please reply if you'd like to keep it.

dev-python/pysrt: support Python 3.5, fix tests, take package

---

x11-libs/libxcb/libxcb-1.11-r1.ebuild

I've been trying to purge python-3.4 from my system in favor of 3.5 and noticed that libxcb's python dependency is build-time only. It can be set to allow python 3.5 without problems.

x11-libs/libxcb: add support for python 3.5

---

x11-misc/compton/compton-0.1_beta2.ebuild
x11-misc/compton/compton-9999.ebuild

I've been trying to purge python-3.4 from my system in favor of 3.5 and noticed that compton's python dependency is build-time only. It can be set to allow python 3.5 without problems.

x11-misc/compton: add support for python 3.5

---

media-video/mpv/mpv-0.15.0-r1.ebuild
media-video/mpv/mpv-9999.ebuild

I've been trying to purge python-3.4 from my system in favor of 3.5 and noticed that mpv's python dependency is build-time only. It can be set to allow python 3.5 without problems.

media-video/mpv: add support for python 3.5

---

media-libs/libepoxy/libepoxy-1.3.1.ebuild
media-libs/libepoxy/libepoxy-9999.ebuild

I've been trying to purge python-3.4 from my system in favor of 3.5 and noticed that libepoxy's python dependency is build-time only. It can be set to allow python 3.5 without problems.

media-libs/libepoxy: add support for python 3.5

---

app-emulation/virtualbox-bin/virtualbox-bin-4.3.32.103443.ebuild

$ emerge -v1 xxx
!!! existing preserved libs:
>>> package: sys-fs/lvm2-2.02.116
*  - /lib64/libdevmapper.so.1.02
*      used by /opt/VirtualBox/VBoxVolInfo (app-emulation/virtualbox-bin-4.3.32.103443)
Use emerge @preserved-rebuild to rebuild packages using these libraries
$ cat /var/lib/portage/preserved_libs_registry 
{
"sys-fs/lvm2:0": [
"sys-fs/lvm2-2.02.116", 
"9802", 
[
"/lib64/libdevmapper.so.1.02"
]
]
}

Rdepend on sys-fs/lvm2 because of /opt/VirtualBox/VBoxVolInfo

---

app-misc/media-player-info/media-player-info-22.ebuild

I've been trying to purge python-3.4 from my system in favor of 3.5 and noticed that media-player-info's python dependency is build-time only. It can be set to allow python 3.5 without problems.

app-misc/media-player-info: add support for python 3.5

---

dev-vcs/gitg/gitg-3.18.0.ebuild

@EvaSDK Here is the pull request we discussed.

dev-vcs/gitg: add support for Python 3.5

---

media-video/mpv/mpv-0.14.0-r1.ebuild

User @Coacher requested python 3.5 support for an older ebuild in PR #779, so here it is.
Tested build/runtime without problems, as expected.

media-video/mpv: add support for python 3.5 to 0.14 series

---

app-text/zathura/zathura-0.3.4.ebuild
app-text/zathura/zathura-9999.ebuild

zathura need a `synctex.pc` for `pkg-config` which is not available in the stable `app-text/texlive-core`. It is available in the next version, which is 2015.
btw, the current 9999 is not building, because of failing patch.

app-text/zathura: synctex need textlive-core-2015

---

dev-libs/uchardet/uchardet-0.0.5-r1.ebuild

cmake_comment_add_subdirectory is EAPI-6-compatible,
while comment_add_subdirectory is not.
Currently both these functions do the same and
this is a ditto change, thus no revbump.

dev-libs/uchardet: avoid using EAPI-6-deprecated function in src_prepare

---

net-libs/tox/files/confd
net-libs/tox/files/initd
net-libs/tox/files/tox-bootstrapd.conf
net-libs/tox/files/tox-bootstrapd.service
net-libs/tox/metadata.xml
net-libs/tox/tox-0_p20160201.ebuild
net-libs/tox/tox-9999.ebuild

Almost in unmodified form from https://github.com/zetok/gentoo-overlay-tox/blob/0955c2a1e373fc07bcb2fefe710bbaa69698ecd9/net-libs/tox/tox-9999.ebuild - I removed maintainer part of `metadata.xml`, since they have resigned from being a maintainer.

net-libs/tox: add ebuild

---

media-video/mpv/mpv-9999.ebuild

libavfilter was made mandatory upstream. We've always enabled it anyway.

media-video/mpv: fix live build

---

dev-db/sqldeveloper/files/sqldeveloper-r1
dev-db/sqldeveloper/sqldeveloper-4.1.3.20.78-r1.ebuild

Java team needs to remove Java 6 ASAP and jtds:1.2 is holding this back. Upstream suggests 1.2 but 1.3 is reported to work. I wasn't able to test against a real database but it did at least try to connect.
Asking users to manually switch their JVM before using this isn't very polite and not usually necessary thanks to Gentoo's launcher scripts. Those scripts cannot feasibly be used here but we can at
least write package.env and use gjl to select the JVM intelligently.
Other fixes:
* Remove java-config from RDEPEND, it's implied by java-pkg-2 eclass.
* RDEPEND on virtual/jre, not virtual/jdk, build tools are unneeded.
* Add some missing dies and remove some unnecessary dies.
* Use newicon instead of mv + doicon.
* Use exec in launcher to prevent lingering process.
@wschlich, please review …

dev-db/sqldeveloper: Use jtds:1.3, auto select 1.8 JVM, other fixes

---

app-portage/cpuinfo2cpuflags/cpuinfo2cpuflags-2.ebuild

app-portage/cpuinfo2cpuflags-2 works on Gentoo/FreeBSD.
Please add KEYWORDS.
```
$ cpuinfo2cpuflags-x86
CPU_FLAGS_X86: aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3
```

app-portage/cpuinfo2cpuflags: Added ~amd64-fbsd ~x86-fbsd keyword.

---

sys-devel/llvm/llvm-3.7.1-r1.ebuild
sys-devel/llvm/llvm-3.8.0_rc1.ebuild

Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=417171
```
+	# Remove unnecessary headers on FreeBSD, bug #417171
+	use kernel_FreeBSD && use clang && rm "${ED}"usr/lib/clang/${PV}/include/{std,float,iso,limits,tgmath,varargs}*.h
```

sys-devel/llvm: Re add the code for Gentoo/FreeBSD.

---

dev-libs/libucl/libucl-0.7.3.ebuild
dev-libs/ucl/ucl-1.03-r1.ebuild

Both libraries opts to use /usr/{include,lib}/libucl* which leads to a conflict. There unfortunately doesn't seem to be a resolution upstream; dev-libs/ucl is 12 years old and dev-libs/libucl has stated that no changes related to this will occur.
ping @gentoo/proxy-maint (co-maintainer)

dev-libs/{lib,}ucl: Avoid simultaneous installation

---

games-strategy/endless-sky/endless-sky-0.8.11.ebuild

games-strategy/endless-sky: fix SRC_URI to point to upstream's repo

---

sys-apps/systemd/systemd-9999.ebuild

systemd-229 [was released](https://lists.freedesktop.org/archives/systemd-devel/2016-February/035748.html) and requires now a `systemd-coredump` user to be present.

sys-apps/systemd: Create "systemd-coredump" user/group

---

dev-ml/qcheck/metadata.xml

dev-ml/qcheck: fix remote-id in metadata.xml

---

media-video/mpv/mpv-9999.ebuild

Instead of forcing Jack1 in the form of media-sound/jack-audio-connection-kit.
Quote from the upstream wiki [0]:
Jack 1 and Jack 2 are equivalent implementations of the same protocol.
...
Programs compiled against Jack 1 will work with Jack 2 without recompile
(and vice versa).
End quote.
[0]: https://github.com/jackaudio/jackaudio.github.com/wiki/Q_difference_jack1_jack2

media-video/mpv: depend on virtual/jack in 9999 when jack USE is enabled

---

net-misc/i2pd/files/i2pd-2.4.0.service
net-misc/i2pd/i2pd-2.4.0-r1.ebuild
net-misc/i2pd/metadata.xml

Oversight on my part when updating i2pd.
@klondi 
@blueness 

net-misc/i2pd: adjust systemd .service to point to /usr/bin/i2pd

---

media-fonts/source-han-sans/source-han-sans-1.001-r1.ebuild

Added the global CJK USEFLAG to source-han-sans so that users with CJK set get Chinese, Japanese, and Korean characters as expected instead of having to enable the linguas_* flags to get them.

media-fonts/source-han-sans: Adding use cjk to be consistent with rdep.

---

net-p2p/syncthing/metadata.xml
net-p2p/syncthing/syncthing-0.12.19.ebuild

switch HOMEPAGE to use 'https://' (redirected by default to it),
description was taken from official repo description,
long description (taken from official site),
also bugs-to link was added

net-p2p/syncthing: fix licence & description, update metadata.xml

---

media-gfx/splash-themes-livecd/files/use-new-path-for-functions.sh.patch
media-gfx/splash-themes-livecd/splash-themes-livecd-2007.0-r3.ebuild

@mgorny 
https://bugs.gentoo.org/show_bug.cgi?id=504394
https://bugs.gentoo.org/show_bug.cgi?id=504116

media-gfx/splash-themes-livecd: Update rc_init-pre to use new path for functions.sh

---

media-gfx/splash-themes-livedvd/files/use-new-path-for-functions.sh.patch
media-gfx/splash-themes-livedvd/splash-themes-livedvd-12.0-r2.ebuild

@mgorny 
https://bugs.gentoo.org/show_bug.cgi?id=504406
https://bugs.gentoo.org/show_bug.cgi?id=504116

media-gfx/splash-themes-livedvd: Update rc_init-pre to use new path for functions.sh

---

app-benchmarks/bonnie++/bonnie++-1.97-r1.ebuild
app-benchmarks/bonnie++/files/bonnie++-1.97-zcav-array-indexing-fix.patch

Also get rid if unnecessary DEPEND and RDEPEND since this package
has no external dependencies.
Remove src_compile phase that was added per #9073 14 years ago.
It's not reproducible anymore.
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=9073
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=309319
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=431684
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=515334

app-benchmarks/bonnie++: eapi bump, fix #309319, #431684, #515334

---

net-libs/librsync/files/librsync-0.9.7-fix-testsuite.patch
net-libs/librsync/librsync-0.9.7-r3.ebuild

Added "librsync-0.9.7-fix-testsuite.patch" to fix compilation of librsync 0.9.7
when "test" feature is enabled in Portage. The patch has been sourced from the
Debian package librsync1-0.9.7-10 and has been provided by Andrey Rahmatullin.
Gentoo-bug: #511954

net-libs/librsync: fix testsuite for v0.9.7, fix bug #511954

---

net-p2p/syncthing/syncthing-0.12.19.ebuild

I've been using it on arm without incident, so I think it's time to add a keyword.
-----
Commit amended to reference preexisting keyword request on BGO.

net-p2p/syncthing: Add ~arm keyword

---

net-libs/librsync/files/librsync-0.9.7-fix-testsuite.patch
net-libs/librsync/librsync-0.9.7-r3.ebuild

Fixed a typo in the ebuild and the testsuite patch for librsync 0.9.7.
Gentoo-bug: #575556

net-libs/librsync: fix typo and patch for v0.9.7

---

dev-lang/go/go-1.6-r2.ebuild

KEYWORDREQ Bug https://bugs.gentoo.org/show_bug.cgi?id=575510
I have confirmed that test is passed on amd64-fbsd/10.2 and x86-fbsd/10.2.
Please add KEYWORDS="~amd64-fbsd ~x86-fbsd" to go-1.6-r2.ebuild.
```
<snip>
ALL TESTS PASSED
>>> Completed testing dev-lang/go-1.6-r2
<snip>
```

dev-lang/go: add ~amd64-fbsd, ~x86-fbsd keyword, bug #575510

---

net-p2p/airdcpp-webclient/airdcpp-webclient-0.16.5.ebuild

Can someone push this simple fix? @monsieurp for instance :)

net-p2p/airdcpp-webclient: add missing depend on net-libs/libnatpmp

---

dev-perl/Any-Moose/Any-Moose-0.260.0-r1.ebuild
dev-perl/Any-Moose/files/nomouse.patch

Short version:
- No runtime changes
- (R)?Deps now only pull Moose
- Tests that cry about Mouse missing nuked
- Circular Any::Moose -> MouseX::Types under FEATURES=test fixed
- EAPI6-and-stuff. 
This is preparation work for eventual removal of Any-Moose from tree,
as it is declared "Deprecated" by upstream, and people who want a
"Be fast by default but still work with Moose" solution are being encouraged
to use Moo instead.
Any-Moose will continue to auto-switch between Moose and Mouse
if Mouse is installed, but will not add any dependencies on Mouse
and will no longer test Mouse based tests, with the idea being to
just force the Moose path by default.
This is effectively what already happened for anyone who installed Moose first,
which is highly likely, because *nothing* in tree other …

dev-perl/Any-Moose: Eliminate dependencies on Mouse

---

dev-perl/Test-Warn/Test-Warn-0.300.0.ebuild

- Tree-DAG_Node usage was already ceased upstream
- Same or Test-Pod
- File::Spec is only used in tests
( no dep rbump because doing so will only remove surplus deps, not add them )
@monsieurp

dev-perl/Test-Warn: Remove excess dependencies

---

app-editors/gummi/gummi-0.6.6.ebuild

Just two minor fixes in 0.6.6 to make repoman happy. Note: This is currently being stabilized in bug #562894

app-editors/gummi: drop base.eclass and fix whitespace

---

dev-perl/Net-OpenID-Common/Net-OpenID-Common-1.200.0.ebuild

Net-OpenID-Consumer was split into two dists, Net-OpenID-Common and Net-OpenID-Consumer,
and so Net-OpenID-Commons files collide with the old version of Net-OpenID-Consumer.
Gentoo-Bug: https://bugs.gentoo.org/576170
@akhuettel @monsieurp

dev-perl/Net-OpenID-Common: Fix collsion with old Net-OpenID-Consumer

---

media-video/bdsup2sub++/bdsup2sub++-1.0.2.ebuild
media-video/bdsup2sub++/files/bdsup2sub++-1.0.2-hidden-config.patch

Patch taken from https://github.com/amichaelt/BDSup2SubPlusPlus/pull/36
Settings will go to `~/.config/bdsup2sub++` instead of `~/bdsup2sub++`

media-video/bdsup2sub++: store settings in a hidden directory

---

net-irc/polari/polari-3.18.1-r1.ebuild

Also added `~arm` keyword as a result of personal testing on a RK3288
(armv7a) device.

net-irc/polari: Add missing RDEPEND on net-im/telepathy-logger

---

media-sound/mpd/mpd-0.19.12.ebuild

In continuation of #587, multi-user.target doesn't exist in the user instance of systemd. Therefore, after enabling, the mpd.service wouldn't autostart. Replace multi-user.target with default.target in the user service file to make it work.

media-sound/mpd: fix the systemd user service

---

dev-vcs/gitg/gitg-3.18.0-r1.ebuild

The gitg fails to start with a kernel patched with grsecurity paches if mprotect is not disabled for its binary.

dev-vcs/gitg: disabled mprotect

---

app-backup/snapper/snapper-9999.ebuild

I have also create a bug report: https://bugs.gentoo.org/show_bug.cgi?id=576556
The ebuild compiles with the renamed README.md

app-backup/snapper: update to reflect renamed README.md

---

games-strategy/endless-sky/endless-sky-0.8.11-r1.ebuild

games-strategy/endless-sky: revbump to 0.8.11-r1, fixing install path

---

sys-devel/llvm/llvm-9999.ebuild

Removed from LLVM SVN in r268631
Signed-off-by: Nick Sarnie <commendsarnex@gmail.com>

sys-devel/llvm: remove CppBackend from 9999

---

dev-python/oslo-i18n/oslo-i18n-2.7.0.ebuild
dev-python/oslo-i18n/oslo-i18n-3.5.0.ebuild
dev-python/oslo-utils/oslo-utils-2.4.0.ebuild
dev-python/oslo-utils/oslo-utils-3.8.0.ebuild
dev-python/oslotest/oslotest-1.10.0.ebuild
dev-python/oslotest/oslotest-1.12.0.ebuild
dev-python/oslotest/oslotest-2.4.0.ebuild
media-sound/aacplusenc/aacplusenc-0.17.5.ebuild

media-sound/aacplusenc was updated to use a new URL which
supports HTTPS on launchpad. Hashes were verified to ensure
they matched up correctly.
@jlec

HTTPS for launchpad.net

---

dev-ruby/travis/travis-1.8.2-r2.ebuild

Travis needs =typhoeus-0.6:
```
travis
/usr/lib64/ruby/site_ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'typhoeus' (>= 0.6.8, ~> 0.6) - did find: [typhoeus-1.0.2] (Gem::LoadError)
```
@gentoo/ruby: works for, but please review!

Fix dev-ruby/travis deps

---

sys-freebsd/freebsd-sources/files/freebsd-ubin-10.3-bmake-workaround.patch
sys-freebsd/freebsd-sources/freebsd-sources-10.3-r3.ebuild

This problem occurs when upgrading from 9.x.
```
>>> Compiling source in /var/tmp/portage/sys-freebsd/freebsd-sources-10.3-r3/work/sys ...
Warning: Object directory not changed from original /var/tmp/portage/sys-freebsd/freebsd-sources-10.3-r3/work/usr.bin/bmake
make: don't know how to make arch.c. Stop
* ERROR: sys-freebsd/freebsd-sources-10.3-r3 failed (compile phase):
*   make failed
```

sys-freebsd/freebsd-sources: Fix the issue that can not build bmake.

---

app-text/wgetpaste/wgetpaste-2.28-r1.ebuild

Many of the paste bins wgetpaste supports require SSL.  This includes
the current default paste bin.  Without wget SSL support, these paste
bins are not accessible.  This change allows wgetpaste to depend on
ssl-enabled wget.
Package-Manager: Portage-2.3.3, Repoman-2.3.1

app-text/wgetpaste: Add wget SSL support

---

dev-lang/nim/nim-0.16.0.ebuild
profiles/arch/arm/armv4/package.mask
profiles/arch/arm/armv4t/package.mask
profiles/arch/arm/armv5te/package.mask

* Tested on armv7a RK3288
* Mask this on armv4 & armv5 because upstream only supports armv6 and newer.

dev-lang/nim: KEYWORD arm

---

sci-mathematics/pari/files/pari-2.3.5-no-dot-inc.patch
sci-mathematics/pari/files/pari-2.5.0-no-dot-inc.patch
sci-mathematics/pari/files/pari-2.7.0-no-dot-inc.patch
sci-mathematics/pari/pari-2.3.5.ebuild
sci-mathematics/pari/pari-2.5.0-r3.ebuild
sci-mathematics/pari/pari-2.5.1-r1.ebuild
sci-mathematics/pari/pari-2.5.1.ebuild
sci-mathematics/pari/pari-2.5.2.ebuild
sci-mathematics/pari/pari-2.5.3.ebuild
sci-mathematics/pari/pari-2.5.4.ebuild
sci-mathematics/pari/pari-2.7.0.ebuild
sci-mathematics/pari/pari-2.7.1.ebuild

Perl 5.26 removes implied cwd from library loading paths, and
subsequently Pari's compile fails due to reliance on this implication.
These patches rectify that by constructing a library path the same
as the scripts directory, and inserting that into `@INC`
Of course, we still need the oldest pari because dev-perl/Math-Pari
needs the old version.
And of course, the files in question have minor changes over the
handful of versions, necessitating 3 *mostly* identical but slightly
different patches for the relevant versions.
I haven't filed this issue upstream, as their bug reporting stuff
looked dizzyingly confusing.
Bug: https://bugs.gentoo.org/615016
Package-Manager: Portage-2.3.6, Repoman-2.3.2

sci-mathematics/pari: Fix for '.' in @INC on perl 5.26 re bug #615016

---

dev-qt/qtwayland/metadata.xml
dev-qt/qtwayland/qtwayland-5.6.2.ebuild
dev-qt/qtwayland/qtwayland-5.7.1.ebuild
kde-frameworks/kwayland/kwayland-5.34.0.ebuild
kde-frameworks/kwayland/kwayland-5.37.0.ebuild
profiles/targets/desktop/plasma/package.use

This is not to say I would merge these changes to stable 5.7.1, but I would like to know what you think about it. For reference: https://bugs.gentoo.org/show_bug.cgi?id=627758#c3
In short, local `USE={egl,gles{,1,2,3}}` flags currently have conflicting implications wrt enabling additional support vs. disabling other. With egl I just picked the lowest hanging fruit to start with, and removal (building it unconditionally) in this case is the most convenient way (at least for a biased KDE team member).

[RFC] dev-qt/qt{gui,wayland}: Drop USE=egl

---

media-video/qx11grab/qx11grab-0.4.12.ebuild

kdelibs4 is deprecated and will be removed eventually.
Dropping support here does not remove anything important, it is limited
to KAboutDialog.
Gentoo-bug: 629018
@gentoo/qt

media-video/qx11grab: Drop USE=kde

---

media-tv/xmltv/files/xmltv-0.5.68-perl526-1.patch
media-tv/xmltv/xmltv-0.5.68.ebuild

Note: If anyone wants to chuck Perl somewhere low on the maintainers list, it might be useful.
Also, there are newer upstream versions, but I didn't bother with it because they don't have these fixes.
Fixes:
- Configure fails without '.' in `@INC`
- Compile fails without '.' in `@INC`
- Compile/Configure fails to use Data::Manip on machines with
gentoo-install-media default setting `TZ=Factory`
Closes: https://bugs.gentoo.org/630474
Package-Manager: Portage-2.3.6, Repoman-2.3.2

media-tv/xmltv:  Fix configure/compile on Perl 5.26 re bug #630474

---

dev-perl/CPAN-Mini-Inject/CPAN-Mini-Inject-0.330.0-r1.ebuild

- No Reverse dependencies
- Has not worked since 2011 due to missing dependencies which nobody
noticed due to tests being disabled ( this will be remedied soon )
Package-Manager: Portage-2.3.8, Repoman-2.3.3

dev-perl/CPAN-Mini-Inject: De-stabilize

---

dev-perl/App-pwhich/App-pwhich-1.150.0.ebuild
dev-perl/DateTime/DateTime-1.420.0.ebuild
profiles/package.mask

Repoman checking 5.26 release and friends.
Post-merge checklist:

profiles: unmask Perl 5.26.0 and 5.26.1

---

dev-qt/qtwebengine/qtwebengine-5.7.1-r2.ebuild

Fix build and ease dependency resolution with a future stable icu-60.2.
Bug: https://bugs.gentoo.org/618648
Package-Manager: Portage-2.3.21, Repoman-2.3.6

dev-qt/qtwebengine: 5.7.1-r2: Switch off USE=-system-icu, fix dep

---

dev-qt/qtwebengine/files/qtwebengine-5.9.4-jpeg-9-1.patch
dev-qt/qtwebengine/files/qtwebengine-5.9.4-jpeg-9-2.patch
dev-qt/qtwebengine/qtwebengine-5.9.4.ebuild

Closes: https://bugs.gentoo.org/607424
Closes: https://bugs.gentoo.org/646456
Built fine against media-libs/jpeg-9c.
Note: This is not yet tested with libjpeg-turbo, but I'm quite confident since patch 2 is quite similar to upstreamed-patch 1.

dev-qt/qtwebengine: Fix build with jpeg-9

---

dev-qt/qtwayland/files/qtwayland-5.9.4-qquickwindow-crash.patch
dev-qt/qtwayland/qtwayland-5.9.4-r1.ebuild

Fixing a runtime crash that affects many users.
Patch taken from 5.9 branch (fixed in 5.9.5).
KDE-Bug: https://bugs.kde.org/show_bug.cgi?id=381630
Qt-Bug: https://bugreports.qt.io/browse/QTBUG-65553
See also: https://codereview.qt-project.org/#/c/210552/
Tested-by: Andrius Štikonas <andrius@stikonas.eu>
Package-Manager: Portage-2.3.24, Repoman-2.3.6

dev-qt/qtwayland: Don't recreate hidden egl surfaces

---

sys-apps/flashrom/flashrom-0.9.6.1.ebuild
sys-apps/flashrom/flashrom-0.9.7.ebuild
sys-apps/flashrom/flashrom-0.9.8.ebuild
sys-apps/flashrom/flashrom-0.9.9.ebuild
sys-apps/flashrom/flashrom-9999.ebuild

Hi,
This PR uses HTTPS for all ebuilds and avoids redirection.
Please review.

sys-apps/flashrom: use https, avoid redirection

---

dev-tcltk/tkimg/files/tkimg-1.4-jpeg-9.patch
dev-tcltk/tkimg/tkimg-1.4-r9.ebuild

Closes: https://bugs.gentoo.org/520886
Only tested with jpeg-9c so far.

dev-tcltk/tkimg: Fix build with jpeg-9

---

media-plugins/kodi-vfs-sftp/kodi-vfs-sftp-9999.ebuild
media-plugins/kodi-vfs-sftp/metadata.xml
media-tv/kodi/kodi-9999.ebuild

Adds support for SFTP to Kodi.
This functionality was originally part of Kodi itself, but was removed in Kodi 18.
Do not merge until https://github.com/xbmc/xbmc/pull/12005 is merged.

WIP media-plugins/kodi-vfs-sftp: SFTP VFS addon for Kodi

---

profiles/arch/arm/package.use.stable.mask
profiles/base/package.use.mask
profiles/default/linux/powerpc/ppc64/13.0/package.use.stable.mask
profiles/default/linux/powerpc/ppc64/17.0/package.use.stable.mask
profiles/prefix/darwin/package.use.mask

@aballier also dropping some fluidsynth, musepack and frei0r *.use.mask entries that are obsolete.

profiles: media-video/vlc cleanup and then some

---

app-text/texlive-core/files/texlive-core-2017-poppler069.patch
app-text/texlive-core/files/texlive-core-2017-poppler071.patch
app-text/texlive-core/files/texlive-core-2017-poppler072.patch
app-text/texlive-core/files/texlive-core-2017-poppler073.patch
app-text/texlive-core/texlive-core-2017-r4.ebuild
profiles/package.mask

Bug: https://bugs.gentoo.org/672854
Not pretty, but at least we're getting there while maybe 2018 is being prepared - and hopefully we can drop most patches then.

app-text/texlive-core: Fix build with poppler-0.71, poppler-0.72 and poppler-0.73

---

profiles/targets/desktop/gnome/package.use
profiles/targets/desktop/make.defaults
profiles/targets/desktop/package.use
profiles/targets/desktop/plasma/package.use

A lot of desktop packages depend on libraries built with USE icu to work;
some, but not nearly enough are currently handled by individual package.use,
leaving users to fix default conflicts.
desktop profile should rather have it enabled globally.

profiles: desktop: Add USE icu to make.defaults

---

dev-qt/qtgui/qtgui-5.14.0.ebuild

With sufficiently parallelised emerge, if dev-qt/qtgui reverse dependencies are
scheduled before modules installing Qt5Gui plugins have been rebuilt, these
revdeps will fail cmake after an incompatible change in macro args.
Bug: https://bugs.gentoo.org/703306
Package-Manager: Portage-2.3.82, Repoman-2.3.20
Signed-off-by: Andreas Sturmlechner <asturm@gentoo.org>

dev-qt/qtgui: Block known old users of _populate_Gui_plugin_properties

---

dev-libs/libgit2/libgit2-0.28.4.ebuild
gui-libs/libwpe/libwpe-1.4.0.1.ebuild
gui-libs/wpebackend-fdo/wpebackend-fdo-1.4.0.ebuild

cmake.class is a slot-in replacement for cmake-utils EAPI-7 (for the most part).

*/*: Switch gnome proj to cmake.eclass

---

app-arch/innoextract/innoextract-1.8.ebuild
dev-db/cpp-driver/cpp-driver-2.11.0.ebuild
dev-libs/hyperscan/hyperscan-5.1.0.ebuild
dev-libs/hyperscan/hyperscan-5.1.1.ebuild
dev-libs/hyperscan/hyperscan-5.2.0.ebuild
dev-util/edb-debugger/edb-debugger-1.0.0-r3.ebuild
dev-util/edb-debugger/edb-debugger-1.1.0-r1.ebuild
dev-util/edb-debugger/edb-debugger-9999.ebuild
dev-util/kdstatemachineeditor/kdstatemachineeditor-1.2.4.ebuild
dev-util/kdstatemachineeditor/kdstatemachineeditor-9999.ebuild
mail-filter/rspamd/rspamd-2.2.ebuild
mail-filter/rspamd/rspamd-9999.ebuild
media-libs/libsoundio/libsoundio-2.0.0.ebuild
media-sound/loudness-scanner/loudness-scanner-0.5.1_p20190709.ebuild
media-sound/loudness-scanner/loudness-scanner-9999.ebuild
net-libs/libsignal-protocol-c/libsignal-protocol-c-2.3.2.ebuild
net-libs/libsignal-protocol-c/libsignal-protocol-c-9999.ebuild
net-libs/tox/tox-0.2.10.ebuild
net-libs/tox/tox-0.2.9-r1.ebuild
net-libs/tox/tox-9999.ebuild

- Only concerns EAPI-7 ported ebuilds
- See also: https://archives.gentoo.org/gentoo-dev/message/3aa1a3aeebad353a7cefcb86a8101943
- Please ACK your packages

*/*: Switch proxy-maint to cmake.eclass

---

dev-ros/rosbag/rosbag-9999.ebuild
eclass/ros-catkin.eclass

Use of EAPI-7 was broken so far because `cmake-utils_use` is banned, actually since EAPI-6.
Closes: https://bugs.gentoo.org/705798
Signed-off-by: Andreas Sturmlechner <asturm@gentoo.org>

ros-catkin.eclass: Fix EAPI-7 support, support cmake.eclass

---

profiles/package.mask

Overarching goal: https://bugs.gentoo.org/698950

Mask dev-python/pygtkglext and revdeps for removal

---

dev-qt/qtdeclarative/files/qtdeclarative-5.14.2-QQuickItemView-fix-maxXY-extent.patch
dev-qt/qtdeclarative/qtdeclarative-5.14.2-r1.ebuild

Works as advertised, gets rid of superfluous scrollbars.
KDE-Bug: https://bugs.kde.org/show_bug.cgi?id=419514
QTBUG: https://bugreports.qt.io/browse/QTBUG-83890
Bug: https://bugs.gentoo.org/716992

dev-qt/qtdeclarative: QQuickItemView: Fix max(X/Y)Extent()

---

x11-misc/compton/compton-0.1_beta2-r1.ebuild

Bug: https://bugs.gentoo.org/718546
Package-Manager: Portage-2.3.97, Repoman-2.3.22
Signed-off-by: Kent Fredric <kentnl@gentoo.org>
-r1 diff:
```diff
--- compton-0.1_beta2.ebuild	2020-02-03 20:00:33.100329069 +1300
+++ compton-0.1_beta2-r1.ebuild	2020-06-17 20:49:43.074592668 +1200
@@ -3,7 +3,7 @@
EAPI=6
-PYTHON_COMPAT=( python3_6 )
+PYTHON_COMPAT=( python3_{6,7,8,9} )
inherit toolchain-funcs python-r1
DESCRIPTION="A compositor for X, and a fork of xcompmgr-dana"
@@ -12,7 +12,7 @@
LICENSE="MIT"
SLOT="0"
-KEYWORDS="amd64 ~ppc x86"
+KEYWORDS="~amd64 ~ppc ~x86"
IUSE="dbus +drm opengl +pcre xinerama"
REQUIRED_USE="${PYTHON_REQUIRED_USE}"
```
- tests pass
- manually testing compton-convgen seemed to indicate its not broken by python updates

x11-misc/compton: Add python 3.7, 3.8 & 3.9 support re bug #718546

---

dev-perl/Ace/Ace-1.920.0-r5.ebuild
dev-perl/Ace/files/Ace-1.92-DARWIN_DEF
dev-perl/Ace/files/Ace-1.92-toolchain.patch

Doing a PR because I need a few eyes to san-check this.
Ebuild diff from -r4
```diff
--- Ace-1.920.0-r4.ebuild	2020-04-23 14:38:29.424768313 +1200
+++ Ace-1.920.0-r5.ebuild	2020-05-19 01:59:13.176504387 +1200
@@ -34,25 +34,27 @@
src_prepare() {
eapply "${FILESDIR}/${PN}-1.92-rpcxs.patch"
eapply "${FILESDIR}/${PN}-1.92-gcc-nonvoid.patch"
-
-	cat > "${S}/acelib/wmake/DARWIN_DEF" <<EOF
-NAME = DARWIN
-COMPILER = $(tc-getCC) -fwritable-strings -DACEDB4 -DPOSIX
-LINKER = $(tc-getLD)
-
-LIBS = -lm
-
-EOF
-
+	eapply "${FILESDIR}/${PN}-1.92-toolchain.patch"
+	cp "${FILESDIR}/${PN}-1.92-DARWIN_DEF" "${S}/acelib/wmake/DARWIN_DEF" || die "can't copy DARWIN_DEF"
if use elibc_glibc || use elibc_musl || use elibc_uclibc ; then
-		# Confusing name, should have been not specific to glibc
-		eapply …
```

dev-perl/Ace: Add CC/AR/LD toolchain love

---

profiles/arch/arm64/package.use.stable.mask

It's going to involve stabilising a newer matplotlib and such,
which we can't do yet.
Signed-off-by: Sam James <sam@gentoo.org>

[CI] profiles/arch/arm64: stable mask app-portage/nattka[depgraph-order]

---

profiles/arch/sparc/use.stable.mask

Signed-off-by: Sam James <sam@gentoo.org>

[CI] profiles/arch/sparc/use.stable.mask: un-stable-mask Python 3.8

---

profiles/package.mask

Bug: https://bugs.gentoo.org/755956

Mask unused KF5 PortingAids for removal

---

eclass/qmake-utils.eclass

Last consumer in Gentoo ebuild repository was dropped.

qmake-utils.eclass: Drop obsolete EAPI-6 support, ban qt4* functions

---

eclass/font.eclass

Almost gone: https://qa-reports.gentoo.org/output/eapi-per-eclass/font.eclass/

font.eclass: Drop EAPI-5 and EAPI-6 support

---

dev-lang/spidermonkey/spidermonkey-78.10.1.ebuild
dev-libs/boost/boost-1.76.0-r1.ebuild

@gentoo/mozilla and @SoapGentoo Please ACK. Thanks.

Remove CMake workaround from boost, and fix prefix build of spidermonkey

---

sci-libs/fftw/fftw-3.3.9.ebuild

thanks @soap for helping this
Closes: https://bugs.gentoo.org/794208
Package-Manager: Portage-3.0.19, Repoman-3.0.3
Signed-off-by: Yixun Lan <dlan@gentoo.org>

sci-libs/fftw: fix two lib path issue for ARCH=riscv

---

app-text/calibre/calibre-5.16.1.ebuild

Bug: https://bugs.gentoo.org/793986
Package-Manager: Portage-3.0.19, Repoman-3.0.3
Signed-off-by: Zac Medico <zmedico@gentoo.org>

app-text/calibre: support SIP v5

---

profiles/package.mask

Bug: https://bugs.gentoo.org/352952

Mask net-print/libgnomecups for removal

---

dev-qt/qtwayland/qtwayland-5.15.2-r14.ebuild

If the observation in the bug is indeed correct, then at least this time we can get away with simply doing the same as in qtcore/qtgui/qtsql.

dev-qt/qtwayland: More fine-grained subslot

---

dev-vcs/subversion/metadata.xml
dev-vcs/subversion/subversion-1.14.1.ebuild

This allows the user to opt into insecure password storage if they truly
desire it.

dev-vcs/subversion: add 'plaintext-password-storage' USE flag

---

eclass/ghc-package.eclass
eclass/haskell-cabal.eclass

Rename function ghc-extractportageversion to ghc-extract-pm-version.
Closes: https://bugs.gentoo.org/843713

ghc-package.eclass: Avoid reserved function name

---

dev-libs/boost/boost-1.79.0.ebuild
dev-libs/boost/files/boost-1.79.0-fix-mips1-transition.patch
profiles/arch/loong/package.mask

Fix upstream issue causing configure errors on multiple arches. Changes
are hand-picked into the dist sources tree. One file rename is reverted
to make scrubbed patch work with patch(1).
Bug: https://bugs.gentoo.org/843212
Signed-off-by: WANG Xuerui <xen0n@gentoo.org>

dev-libs/boost: fix build for 1.79.0

---

media-libs/libjxl/libjxl-0.7.0_pre20220329.ebuild

Bug: https://bugs.gentoo.org/856037

media-libs/libjxl: unkeyword 0.7.0_pre20220329 for !arm

---

media-plugins/gst-plugins-libnice/metadata.xml
net-im/telepathy-connection-managers/metadata.xml
net-libs/farstream/metadata.xml
net-libs/libnice/metadata.xml
net-libs/sofia-sip/metadata.xml
net-libs/telepathy-farstream/metadata.xml
net-voip/telepathy-gabble/metadata.xml
net-voip/telepathy-rakia/metadata.xml
net-voip/telepathy-salut/metadata.xml

Once GNOME 42 is gone †, GNOME packages ‡ will only have a dependence on a couple of telepathy packages:
- `net-im/telepathy-logger`
- `net-im/telepathy-mission-control`
- `net-irc/telepathy-idle`
- `net-libs/telepathy-glib`
The rest continue to have reverse dependencies outside of GNOME, so we can't remove them trivially. Telepathy seems to be wholly unmaintained, so drop the gnome@ team's maintainership.
KDE/Qt may want to take over maintainership of some of these, as they still have reverse dependencies. Cc: @gentoo/kde, @gentoo/qt.
† specifically, `gnome-base/gnome-shell`, `gnome-extra/gnome-contacts`, and `gnome-extra/gnome-shell-extensions`
‡ specifically `dev-libs/folks` and `net-irc/polari`

Drop gnome@ as a maintainer from telepathy packages

---

profiles/default/linux/make.defaults
profiles/releases/17.0/make.defaults

This is an obsolete profile entry from the days when IUSE defaults did not exist.
Bug: https://bugs.gentoo.org/890999

profiles: move USE="fortran openmp" from default/linux to releases/17.0

---

dev-util/glslang/glslang-1.3.239.ebuild
dev-util/glslang/glslang-9999.ebuild
dev-util/spirv-headers/spirv-headers-1.3.239.ebuild
dev-util/spirv-headers/spirv-headers-99999999.ebuild
dev-util/spirv-tools/spirv-tools-1.3.239.ebuild
dev-util/spirv-tools/spirv-tools-99999999.ebuild
dev-util/vulkan-headers/vulkan-headers-1.3.239.ebuild
dev-util/vulkan-headers/vulkan-headers-9999.ebuild
dev-util/vulkan-tools/vulkan-tools-1.3.239.ebuild
dev-util/vulkan-tools/vulkan-tools-9999.ebuild
media-libs/vulkan-layers/vulkan-layers-1.3.239.ebuild
media-libs/vulkan-layers/vulkan-layers-9999.ebuild
media-libs/vulkan-loader/vulkan-loader-1.3.239.ebuild
media-libs/vulkan-loader/vulkan-loader-9999.ebuild

*9999* ebuilds first, current ~arch commits in second wave.
There's one thing I don't understand in dev-util/spirv-tools:
```
COMMON_DEPEND="~dev-util/spirv-headers-1.3.239"
DEPEND="${COMMON_DEPEND}"
RDEPEND=""
BDEPEND="${PYTHON_DEPS}
${COMMON_DEPEND}"
```
If this is really a thing, that the build system requires headers in BDEPEND in addition to DEPEND, maybe the reasoning should be put into a comment for others to understand.

Vulkan stuff EAPI-8 bumps and micro cleanups

---

dev-libs/libclc/libclc-15.0.7.ebuild
dev-libs/libclc/libclc-16.0.3.ebuild
dev-libs/libclc/libclc-16.0.4.ebuild
dev-libs/libclc/libclc-16.0.5.9999.ebuild
dev-libs/libclc/libclc-17.0.0.9999.ebuild
dev-libs/libclc/libclc-17.0.0_pre20230502.ebuild
dev-libs/libclc/libclc-17.0.0_pre20230512.ebuild
dev-libs/libclc/libclc-17.0.0_pre20230520.ebuild

mesa-23.1.0 depends on libclc[spirv] in some common use cases (and media-libs/mesa is libclc's only consumer in ::gentoo).

dev-libs/libclc: Enable USE=spirv by default

---

profiles/base/make.defaults

In preparation for OpenSSL 3.
Bug: https://bugs.gentoo.org/797676

profiles/base: change to PHP_TARGETS="php8-1"

---

metadata/install-qa-check.d/08gentoo-paths

Bug: https://bugs.gentoo.org/912354

metadata/install-qa-check.d: Check for subdirs in /bin and its friends

---

net-irc/quassel/files/quassel-0.14.0-fix-desktop-application-name.patch
net-irc/quassel/quassel-0.14.0-r2.ebuild
net-irc/quassel/quassel-9999.ebuild

- dev-qt/qtscript dependency was dropped in upstream commit
42d328e94a3bed8e6b0a32e7a234281e6d184325
- add missing dev-qt/qttest:5 slot dep
- drop unused IUSE debug
- style fixes (one dep per line, unnecessary DEPEND append)
- fix broken elog link (use https)
- missing || die
- use optfeature

net-irc/quassel: update EAPI 7 -> 8, drop unused dev-qt/qtscript

---

dev-qt/qtgui/qtgui-5.15.11-r1.ebuild
kde-plasma/kwin/files/kwin-5.27.9-xdgshellwindow-enforce-min-size.patch
kde-plasma/kwin/kwin-5.27.9-r1.ebuild
profiles/targets/desktop/package.use

This exists since way before I looked at `dev-qt/*`, was there a reason to omit the build system switch or dependency that I am not aware of?
```diff
--- qtgui-5.15.11.ebuild        2023-11-08 21:05:05.104914553 +0100
+++ qtgui-5.15.11-r1.ebuild     2023-11-08 21:05:26.538147361 +0100
@@ -5,7 +5,7 @@
if [[ ${PV} != *9999* ]]; then
QT5_KDEPATCHSET_REV=2
-       KEYWORDS="amd64 arm arm64 ~hppa ~loong ppc ppc64 ~riscv ~sparc x86"
+       KEYWORDS="~amd64 ~arm ~arm64 ~hppa ~loong ~ppc ~ppc64 ~riscv ~sparc ~x86"
fi
QT5_MODULE="qtbase"
@@ -33,6 +33,7 @@
media-libs/freetype:2
media-libs/harfbuzz:=
sys-libs/zlib:=
+       accessibility? ( app-accessibility/at-spi2-core:2 )
dbus? ( =dev-qt/qtdbus-${QT5_PV}* )
eglfs? (
media-libs/mesa[gbm(+)]
@@ -150,6 +151,7 @@
src_configure() {
local myconf=(
+ …
```

dev-qt/qtgui: Wire up IUSE=accessibility, add missing dependency

---

dev-python/aiohttp/aiohttp-3.9.1.ebuild
dev-python/aiohttp/aiohttp-3.9.2.ebuild
dev-python/aiohttp/aiohttp-3.9.3.ebuild
dev-python/astroid/astroid-3.0.2.ebuild
dev-python/astroid/astroid-3.0.3.ebuild
dev-python/lark/lark-1.1.9.ebuild
dev-python/re-assert/re-assert-1.1.0-r1.ebuild
dev-python/regex/regex-2023.12.25.ebuild
dev-python/rfc3987/rfc3987-1.3.8-r2.ebuild
dev-python/tox/tox-4.12.1.ebuild

It's unsupported upstream and on x86 at least, it ends up showing up precisely
because of the UTF8-vs-ASCII strings representation problem.
(See also mrabarnett/mrab-regex#404 where the
test issues got fixed but upstream made clear that it's unsupported and
also can't really work properly.)
Bug: mrabarnett/mrab-regex#404
Bug: mrabarnett/mrab-regex#521
Closes: https://bugs.gentoo.org/924136
Signed-off-by: Sam James <sam@gentoo.org>

dev-python/regex: disable pypy3

---

profiles/arch/powerpc/ppc32/package.mask
profiles/arch/powerpc/ppc32/package.use.mask
sys-libs/libomp/libomp-15.0.7-r6.ebuild
sys-libs/libomp/libomp-16.0.6.ebuild
sys-libs/libomp/libomp-17.0.6.ebuild
sys-libs/libomp/libomp-18.1.2.ebuild

It never worked.
Bug: https://bugs.gentoo.org/600148
Bug: https://bugs.gentoo.org/708344
Closes: https://bugs.gentoo.org/907213

sys-libs/libomp: drop ppc (isn't supported)

---

eclass/common-lisp-3.eclass

common-lisp-3.eclass: Drop support for EAPI 6

---

profiles/targets/desktop/plasma/package.use

Required by kde-plasma/kwin:6.

profiles: desktop/plasma: Add x11-base/xwayland[libei] to package.use

---

profiles/arch/hppa/package.use.mask
profiles/arch/hppa/package.use.stable.mask
profiles/arch/powerpc/ppc32/package.use.mask
profiles/arch/powerpc/ppc64/package.use.mask
profiles/arch/sparc/package.use.mask
profiles/arch/sparc/package.use.stable.mask

profiles: powerpc/*,hppa,sparc: Drop dev-util/cmake[gui] mask

---

x11-libs/libdrm/libdrm-2.4.122-r1.ebuild
x11-libs/libdrm/libdrm-2.4.123-r1.ebuild
x11-libs/libdrm/libdrm-9999.ebuild

The man pages are just man3 and man7, so unlikely to be used.
Avoids a circular dependency as well:
```
(x11-libs/libdrm-2.4.122:0/0::gentoo, ebuild scheduled for merge) depends on
(dev-python/docutils-0.21.2-1:0/0::gentoo, binary scheduled for merge) (buildtime)
(dev-python/pillow-10.4.0:0/0::gentoo, ebuild scheduled for merge) (runtime)
(media-libs/libwebp-1.3.2:0/7::gentoo, ebuild scheduled for merge) (buildtime_slot_op)
(virtual/opengl-7.0-r2:0/0::gentoo, ebuild scheduled for merge) (buildtime)
(media-libs/mesa-24.1.6:0/0::gentoo, ebuild scheduled for merge) (runtime)
(x11-libs/libdrm-2.4.122:0/0::gentoo, ebuild scheduled for merge) (buildtime)
```

x11-libs/libdrm: Add IUSE=doc to control man pages

---

dev-python/python-multipart/files/python-multipart-0.0.12-rename.patch
dev-python/python-multipart/python-multipart-0.0.12-r100.ebuild
dev-python/starlette/starlette-0.39.2-r1.ebuild
dev-python/starlette/starlette-0.41.0-r1.ebuild
dev-python/starlette/starlette-0.41.0-r2.ebuild
net-im/synapse/synapse-1.113.0-r1.ebuild
net-im/synapse/synapse-1.114.0-r1.ebuild
net-im/synapse/synapse-1.115.0-r2.ebuild
net-im/synapse/synapse-1.116.0-r1.ebuild
net-im/synapse/synapse-1.116.0-r2.ebuild

Following similar concept as https://github.com/Kludex/python-multipart/pull/166 ; except that we don't need the compatibility thingy, we instead patch the revdeps. This will enable add to us `dev-python/multipart` and start unbundling it everywhere where `python-multipart` conflict forced it to be bundled.

dev-python/python-multipart: rename the Python package to `python_multipart`

---

sys-apps/iproute2/iproute2-6.11.0-r2.ebuild
sys-apps/iproute2/iproute2-9999.ebuild

Per discussion in IRC, use the upstream default and allow users to override it using EXTRA_ECONF.
Closes: https://bugs.gentoo.org/935049

sys-apps/iproute2: disable color again

---

sys-libs/glibc/glibc-2.40-r7.ebuild
sys-libs/glibc/glibc-9999.ebuild

```
sys-libs/glibc: run fixincludes in pkg_postinst
We enabled fixincludes for a window between GCC 13 and whatever the just
released version of glibc was at the time to cover Float128 changes. We
then turned it off again when it was (mostly) no longer needed.
(Though arguably it was/still is needed for some upgrade paths or combinations
and maybe we should reconsider that given we now have a proper solution here
to "defanging" fixincludes (as it turns out we were kind of using it wrong,
see bug #30701)).
Anyway, for any glibc installed during that window, a fixincludes'd pthread.h
would've been installed to the include-fixed directory, which then becomes
a cached stale copy when the rest of glibc changes like:
```
--- pthread.h-fixincludes       2024-12-12 06:49:06.918089635 +0000
+++ …

sys-libs/glibc: run fixincludes in pkg_postinst

---

dev-build/muon/muon-0.4.0.ebuild

Closes: https://bugs.gentoo.org/950568

dev-build/muon: Add missing dev-util/gdbus-codegen test dep

---

dev-libs/glib/glib-2.78.6.ebuild
dev-libs/glib/glib-2.80.5-r1.ebuild
dev-libs/glib/glib-2.82.5.ebuild
dev-libs/glib/glib-2.84.0.ebuild
dev-libs/glib/glib-2.84.1.ebuild
dev-util/sysprof-capture/sysprof-capture-3.48.0.ebuild
dev-util/sysprof-capture/sysprof-capture-46.0.ebuild
dev-util/sysprof-capture/sysprof-capture-47.2.ebuild
eclass/dot-a.eclass
eclass/tests/dot-a.sh
sys-devel/flex/flex-2.6.4-r6.ebuild
sys-libs/zlib/zlib-1.3.1-r1.ebuild

This needs more testing still as well as some decisions on where to put QA checks (and they should be opt-in as well).
---
Introduce a new eclass with utility functions for handling LTO bytecode (or internal representation, IR) inside static archives (.a files).
Static libraries when built with LTO will contain LTO bytecode which is not portable across compiler versions or compiler vendors. To avoid pessimising the library and always filtering LTO, we can build it with -ffat-lto-objects instead, which builds some components twice. The installed part will then have the LTO contents stripped out, leaving the regular objects in the static archive.
It's not feasible to make these work otherwise, as we'd need tracking for whether a library was built by a specific compiler and its version, and …

dot-a.eclass: new eclass for handling LTO in static archives

---

profiles/package.mask

profiles: Mask kde-frameworks/kinit for removal

---

profiles/package.mask

This is the only package blocking libzip[static-libs] cleanup. Which is cause for a lot of ebuild complexity and broken wrt deps anyway.
The alternative would be to drop IUSE static or limit it to !libzip, but I don't want to spend time on something that is potentially dead and unneeded.
@zmedico please let me know what to do.

profiles: Mask sys-boot/vboot-utils for removal

---

dev-build/autoconf-vanilla/autoconf-vanilla-2.69-r1.ebuild
dev-build/autoconf-vanilla/autoconf-vanilla-2.71-r1.ebuild
dev-build/autoconf-vanilla/autoconf-vanilla-2.72-r1.ebuild
dev-build/autoconf-vanilla/autoconf-vanilla-9999.ebuild
dev-build/autoconf/autoconf-2.69-r10.ebuild
dev-build/autoconf/autoconf-2.71-r8.ebuild
dev-build/autoconf/autoconf-2.72-r3.ebuild
dev-build/autoconf/autoconf-9999.ebuild

The app-emacs package overrides the autoconf mode that is included with Emacs proper, which may not be wanted by all users.
Bug: https://bugs.gentoo.org/959856
---

dev-build/autoconf{,-vanilla}: Drop PDEPEND on app-emacs/autoconf-mode

---

app-cdr/cdrtools/cdrtools-3.02_alpha09-r5.ebuild
app-emulation/qemu/qemu-10.0.0.ebuild
app-emulation/qemu/qemu-10.0.2-r50.ebuild
app-emulation/qemu/qemu-10.0.2.ebuild
app-emulation/qemu/qemu-10.0.3.ebuild
app-emulation/qemu/qemu-9.1.3-r2.ebuild
app-emulation/qemu/qemu-9.2.3-r3.ebuild
app-emulation/qemu/qemu-9.2.4.ebuild
app-emulation/qemu/qemu-9999.ebuild
app-i18n/fbterm/fbterm-1.7_p20190503.ebuild
eclass/fcaps.eclass
gui-apps/swaylock/swaylock-1.8.0.ebuild
gui-apps/swaylock/swaylock-9999.ebuild
sys-libs/pam/pam-1.7.0_p20241230-r3.ebuild
sys-libs/pam/pam-1.7.1.ebuild
x11-misc/slock/slock-1.5.ebuild
x11-misc/slock/slock-1.6.ebuild

Update fcaps.eclass to avoid setting the suid bit by default when file capabilities are disabled.
I also did a scan of packages inheriting fcaps and added `-m u+s` where I felt it was appropriate. It is possible I missed some, but I think the risk is fairly small and it should be easy for maintainers to correct at a later date if necessary.
Bug: https://bugs.gentoo.org/811105

fcaps.eclass: do not set suid bit as a fallback

---

profiles/arch/arm/package.use.mask
profiles/arch/arm/use.mask
profiles/arch/arm64/package.use.mask
profiles/arch/arm64/package.use.stable.mask
profiles/arch/arm64/use.stable.mask
profiles/arch/base/package.use.mask
profiles/arch/hppa/package.use.mask
profiles/arch/powerpc/ppc64/package.use.mask
profiles/arch/sparc/package.use.mask
profiles/arch/sparc/use.mask
profiles/arch/x86/package.use.mask

For a while now, we mask USE=vulkan entirely on arches where it's not available. Drop some stale per-package mask-in-base-then-unmask patterns which had e.g. mpv[vulkan] unnecessarily masked on arm64.

profiles/arch: drop obsolete per-package USE=vulkan masks
