gentoo/gentoo

dev-util/idea-ultimate/idea-ultimate-14.1.4.141.1532.4.ebuild, dev-util/idea-ultimate/idea-ultimate-15.0.0.142.3926.4_pre.ebuild
def-util/idea-ultimate:  corrected SRC_URI
* with constantly changing the ebuilds for the initial import #20 I deleted one character from the SRC_URI by accident, this commit has the working URI. 
* Also I changed the ebuild of the pre-release to be hard-masked.
Signed-off-by: Gert Pellin <gert@gepe-biljarts.be>
=> dev-util/idea-ultimate: corrected SRC_URI

dev-python/ipython/files/ipython-3.2.1-Don-t-redirect-from-edit-to-files.patch, dev-python/ipython/files/ipython-3.2.1-only-redirect-to-editor-for-text-documents.patch, dev-python/ipython/files/ipython-3.2.1-set-mime-type-on-files.patch, dev-python/ipython/files/ipython-3.2.1-set-model-mimetype-even-when-content-False.patch, dev-python/ipython/ipython-3.2.1-r1.ebuild
"Maliciously crafted text files in IPython/Jupyter editor"
http://seclists.org/oss-sec/2015/q3/558
https://bugs.gentoo.org/show_bug.cgi?id=560708
=> dev-python/ipython: Fix security issue

media-libs/libgltf/libgltf-0.0.1.ebuild, media-libs/libgltf/libgltf-0.0.2.ebuild, media-libs/libgltf/libgltf-9999.ebuild
=> media-libs/libgltf: Add slot operator on media-libs/glew

dev-db/postgresql/postgresql-9.0.21.ebuild, dev-db/postgresql/postgresql-9.0.22.ebuild, dev-db/postgresql/postgresql-9.1.17.ebuild, dev-db/postgresql/postgresql-9.1.18.ebuild, dev-db/postgresql/postgresql-9.2.12.ebuild, dev-db/postgresql/postgresql-9.2.13.ebuild, dev-db/postgresql/postgresql-9.3.8.ebuild, dev-db/postgresql/postgresql-9.3.9.ebuild, dev-db/postgresql/postgresql-9.4.3.ebuild, dev-db/postgresql/postgresql-9.4.4-r1.ebuild, dev-db/postgresql/postgresql-9.4.4.ebuild, dev-db/postgresql/postgresql-9.5_alpha1.ebuild, dev-db/postgresql/postgresql-9999.ebuild
See https://bugs.gentoo.org/show_bug.cgi?id=559884
=> dev-db/postgresql: use /bin/sh instead of /bin/bash for postgres user

sys-apps/paludis/metadata.xml
* set useful local description for xml
* use `<pkg>...</pkg>` syntax
@mgorny @jdhore
=> sys-apps/paludis: update metadata.xml

media-libs/libass/files/0.13.0-configure-Set-the-correct-x32-machine-option-for-yas.patch, media-libs/libass/libass-0.13.0.ebuild
=> media-libs/libass: Fix building for x32, bug #509460

dev-java/bcmail/bcmail-1.38-r5.ebuild, dev-java/bcmail/bcmail-1.45-r4.ebuild, dev-java/bcmail/bcmail-1.50-r2.ebuild, dev-java/bcmail/bcmail-1.52-r2.ebuild, dev-java/bcpkix/bcpkix-1.50-r2.ebuild, dev-java/bcprov/bcprov-1.50-r4.ebuild, dev-java/bcprov/bcprov-1.52-r3.ebuild, dev-java/itext/itext-5.5.4-r2.ebuild
This is a PR that is meant to be fixing https://bugs.gentoo.org/show_bug.cgi?id=563272. I want the CI tests to pass and I will merge it afterwards.
=> dev-java/bc: SLOTs set up

dev-ml/ocaml-cstruct/ocaml-cstruct-1.7.0-r1.ebuild, dev-ml/ocaml-uri/ocaml-uri-1.9.1-r1.ebuild, dev-ml/ocplib-endian/ocplib-endian-0.8-r1.ebuild, dev-ml/stringext/stringext-1.4.0-r1.ebuild, dev-ml/zarith/zarith-1.3-r1.ebuild
required updates due to minor oversight.
@aballier : what about [those](https://bpaste.net/show/6bd49ddfcd5f)?
=> dev-ml/{stringext,ocaml-{cstruct,endian,uri}}: revbumps

eclass/java-mvn-src.eclass, eclass/java-osgi.eclass, eclass/java-pkg-simple.eclass
This a long overdue bugfix for https://bugs.gentoo.org/show_bug.cgi?id=476946. Chewi will review it and sign off on it for merging.
=> java-{mvn-src,osgi,pkg-simple}.eclass: Rewrite documentation to make it compliant with the new style. 

eclass/java-pkg-simple.eclass, eclass/java-utils-2.eclass
This a PR for @chewi about a problem we discussed in #gentoo-java.
=> java-{utils-2,pkg-simple}.eclass: Improve logging.

app-text/pdfgrep/pdfgrep-1.4.1-r1.ebuild
=> app-text/pdfgrep-1.4.1: Fix pcre use flag

app-office/libreoffice/libreoffice-9999.ebuild
gconf: see commit 3cf557c12d27f1b2250e69a543136da098112d80
@akhuettel
=> app-office/libreoffice: Drop gconf integration, python2_7 support

www-servers/tomcat/tomcat-8.0.28-r2.ebuild
@gentoo/java @chewi @monsieurp Added sed to add missing docBase to host-manager and manager webapps context.xml files
=> www-servers/tomcat: Added missing docBase to webapps context.xml files

app-laptop/i8kutils/files/i8kutils-1.42-Makefile.patch, app-laptop/i8kutils/files/i8kutils-gcc5.patch, app-laptop/i8kutils/i8kutils-1.42.ebuild
Also do recipe enhancements requested by the same bug report #565466
Signed-off-by: Ioan-Adrian Ratiu <adi@adirat.com>
=> app-laptop/i8kutils: fix gcc5 build for v1.42

net-analyzer/ndoutils/ndoutils-2.0.0.ebuild
=> net-analyzer/ndoutils: Install ndo2db and ndomod.o appropriate to nagios version

dev-python/pyflakes/pyflakes-1.0.0.ebuild
The actual location is `files/1.0.0-fix-pypy-tests.patch`
=> dev-python/pyflakes: Fix location of patch

sys-freebsd/freebsd-cddl/freebsd-cddl-10.2.ebuild, sys-freebsd/freebsd-lib/freebsd-lib-10.2-r1.ebuild, sys-freebsd/freebsd-rescue/freebsd-rescue-10.2.ebuild, sys-freebsd/freebsd-sbin/freebsd-sbin-10.2.ebuild, sys-freebsd/freebsd-share/freebsd-share-10.2.ebuild, sys-freebsd/freebsd-sources/freebsd-sources-10.2-r1.ebuild, sys-freebsd/freebsd-ubin/freebsd-ubin-10.2-r1.ebuild, sys-freebsd/freebsd-usbin/freebsd-usbin-10.2-r4.ebuild
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=566522
=> sys-freebsd: Move use call from global scope to pkg_setup.

net-wireless/broadcom-sta/broadcom-sta-6.30.223.271-r2.ebuild, net-wireless/broadcom-sta/files/broadcom-sta-6.30.223.271-linux-4.3.patch
https://bugs.gentoo.org/show_bug.cgi?id=565254
@mpagano @mattst88
=> net-wireless/broadcom-sta: patch for compatibility with kernel-4.3

app-admin/ulogd/ulogd-2.0.5-r2.ebuild, app-admin/ulogd/ulogd-2.0.5-r3.ebuild
- Use HTTPS site for HOMEPAGE
- Add and prefer HTTPS mirror in SRC_URI
- Make DOCS stand out
- Remove unneeded die message
- Do not hardcode paths
=> app-admin/ulogd: minor ebuild updates

app-text/linuxdoc-tools/files/linuxdoc-tools-0.9.71-fix-parallel-doc-build.patch, app-text/linuxdoc-tools/linuxdoc-tools-0.9.71-r1.ebuild
Addresses QA warning when built with '+doc' USE. Minor ebuild cleanups.
=> app-text/linuxdoc-tools: fix parallel doc build

dev-python/nbconvert/files/nbconvert-4.1.0-docs-Makefile.patch, dev-python/nbconvert/nbconvert-4.1.0.ebuild
@jlec I missed to add this patch, please merge.
=> dev-python/nbconvert: Add missing patch

app-admin/lastpass/metadata.xml
=> app-admin/lastpass: add long description in metadata

x11-misc/virtualgl/files/vgl.initd-r3, x11-misc/virtualgl/virtualgl-2.4.1-r3.ebuild
This fixes a race condition in the openrc script.
Gentoo-Bug: 569226
Suggested-By: Jason Schulz <jason@schulz.name>
=> x11-misc/virtualgl: race condition fix

sci-libs/cdd+/cdd+-077a.ebuild, sci-libs/cdd+/files/cdd+-077a-gcc-5.patch, sci-libs/cdd+/files/cdd+-077a-qa-const-char.patch
=> sci-libs/cdd+: Gentoo-Bug: 569222, fix for GCC-5.

media-video/mpv/mpv-9999.ebuild
=> media-video/mpv: sync live ebuild with upstream

sci-mathematics/fann/fann-9999.ebuild
=> sci-mathematics/fann: add fann-9999 ebuild

dev-python/jupyter_core/jupyter_core-4.0.6.ebuild
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=571652
@jlec Please merge.
=> dev-python/jupyter_core: Add ipython as dependency for testing

media-video/mpv/mpv-9999.ebuild
=> media-video/mpv: add support for vaapi-drm configure option to 9999

dev-libs/uchardet/files/uchardet-0.0.5-fix-return-code-on-error.patch, dev-libs/uchardet/uchardet-0.0.5-r1.ebuild
=> dev-libs/uchardet: revbump to 0.0.5-r1 to fix return code on error

x11-wm/awesome/metadata.xml
=> x11-wm/awesome: remove myself from maintainers

app-text/sigil/metadata.xml, dev-ml/mirage-profile/metadata.xml, dev-ml/ocaml-cstruct/metadata.xml, dev-ml/ocaml-dns/metadata.xml, dev-ml/ocaml-pcap/metadata.xml, dev-ml/ocaml-uri/metadata.xml, dev-ml/ocplib-endian/metadata.xml, dev-ml/qcheck/metadata.xml, dev-ml/stringext/metadata.xml, net-misc/libres3/metadata.xml, net-misc/sx/metadata.xml, net-wireless/broadcom-sta/metadata.xml
To fix some broken tools, I added the <name> tag to all the metadata files i'm listed in.
=> update my packages' metadata.xml to contain a name-tag

media-video/aegisub/files/aegisub-9999-add-missing-pthread-flags.patch
=> media-video/aegisub: update 9999 patchset

app-text/sigil/metadata.xml
=> app-text/sigil: update remote-id in metadata.xml

media-libs/virglrenderer/virglrenderer-9999.ebuild
Signed-off-by: Nick Sarnie <commendsarnex@gmail.com>
=> media-libs/virglrenderer: Update git repository for 9999

www-client/firefox/firefox-44.0.2.ebuild
https://www.mozilla.org/en-US/firefox/44.0.1/releasenotes/
=> www-client/firefox: nss>=3.21 is a must now

media-video/mpv/mpv-0.9.2-r1.ebuild
=> media-video/mpv: restrict 0.9.2-r1 to ffmpeg < 3.0 wrt bug 575146

mail-filter/dcc/dcc-1.3.158.ebuild, mail-filter/libspf2/libspf2-1.2.10.ebuild, mail-filter/libsrs_alt/libsrs_alt-1.0.ebuild, mail-filter/opendmarc/opendmarc-1.3.1.ebuild, mail-mta/exim/exim-4.86-r2.ebuild, net-dialup/freeradius-client/freeradius-client-1.1.7.ebuild
=> Keyword mail-mta/exim & dependencies on ~arm

app-admin/keepassx/keepassx-2.0.2.ebuild
=> app-admin/keepassx: Add ~arm keyword

dev-ruby/travis/travis-1.8.2-r1.ebuild
=> dev-ruby/travis: install bash-comp as well

app-admin/collectd/collectd-5.4.1-r2.ebuild, app-admin/collectd/collectd-5.5.0.ebuild, app-admin/collectd/collectd-5.5.1.ebuild
This will fix https://bugs.gentoo.org/show_bug.cgi?id=540750
=> app-admin/collectd: Adjust dependency on sys-power/nut (#540750)

dev-java/json/metadata.xml, dev-util/cccc/metadata.xml, sci-electronics/quartus-prime-lite/metadata.xml
Various issues flagged by repoman.
=> Metadata fixes

dev-perl/math-pari/math-pari-2.10.808.ebuild
=> dev-perl/math-pari: Add missing DEPEND on app-arch/unzip

media-video/mplayer/metadata.xml, media-video/mplayer/mplayer-1.2.1.ebuild, media-video/mplayer/mplayer-1.3.0.ebuild, media-video/mplayer/mplayer-9999.ebuild
> vcd : Enables VCD support
> yuv4mpeg : Enables yuv4mpeg video output
=> media-video/mplayer: add vcd and yuv4mpeg USE flags (bug #574806)

media-libs/ffmpegsource/metadata.xml
=> media-libs/ffmpegsource: add subslot description to metadata.xml

net-misc/strongswan/strongswan-5.3.4-r1.ebuild
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>
=> net-misc/strongswan plugin unbound needs net-libs/ldns

eclass/latex-package.eclass
allow passing arguments to tex compiler
=> latex-package.eclass:  allow passing arguments to pdflatex

media-libs/portaudio/portaudio-19_pre20140130.ebuild, media-sound/lingot/lingot-0.9.1.ebuild, media-sound/lmms/lmms-1.1.3.ebuild, media-sound/pulseaudio/pulseaudio-8.0.ebuild, media-sound/qjackctl/qjackctl-0.4.1-r2.ebuild
They work just nice with JACK2.
PS: we need some mass migration.
=> Migrate some ebuilds to virtual/jack

sys-process/atop/atop-2.2.ebuild, sys-process/atop/files/atop.service, sys-process/atop/files/atopacct.service
https://bugs.gentoo.org/show_bug.cgi?id=553310
=> sys-process/atop: systemd support

net-nntp/pan/files/pan-0.139-r2-fix_crash_at_startup.patch, net-nntp/pan/pan-0.139-r2.ebuild
=> net-nntp/pan: fix crash at startup

sys-libs/db/db-5.1.29-r1.ebuild, sys-libs/db/db-5.3.28-r2.ebuild, sys-libs/db/files/db-5.1.29-rename-atomic-compare-exchange.patch
Gentoo-Bug: https://bugs.gentoo.org/417547
=> sys-libs/db: fix compiling with clang

games-arcade/savagewheels/savagewheels-1.6.1-r1.ebuild
Package-Manager: portage-2.3.0
=> games-arcade/savagewheels: Remove games directory from paths

net-im/ejabberd/ejabberd-16.01-r1.ebuild, net-im/ejabberd/ejabberd-16.04.ebuild, net-im/ejabberd/ejabberd-2.1.13-r2.ebuild
https://bugs.gentoo.org/show_bug.cgi?id=588272
=> net-im/ejabberd: require <dev-lang/erlang-19

app-admin/rex/metadata.xml, app-admin/rex/rex-9999.ebuild
I'm doing some rather weird stuff here, so some sort of review feedback in case I'm doing anything particularly dense, or there's something I could do better. 
Thanks.
=> app-admin/rex: Add -9999 ebuild

dev-libs/spdlog/files/spdlog-0.14.0-CMakeLists.txt, dev-libs/spdlog/spdlog-0.14.0-r1.ebuild
=> dev-libs/spdlog: Use GNUInstalldirs, fix cmake files location

dev-python/PyQt5/PyQt5-5.10.1.ebuild, dev-python/PyQt5/PyQt5-5.9.2.ebuild, dev-qt/qtpositioning/qtpositioning-5.11.0_rc2.ebuild, dev-qt/qtpositioning/qtpositioning-5.9.5.ebuild, dev-qt/qtsensors/qtsensors-5.11.0_rc2.ebuild, dev-qt/qtsensors/qtsensors-5.9.5.ebuild, dev-qt/qtserialport/qtserialport-5.11.0_rc2.ebuild, dev-qt/qtserialport/qtserialport-5.9.5.ebuild, dev-qt/qtwebchannel/qtwebchannel-5.11.0_rc2.ebuild, dev-qt/qtwebchannel/qtwebchannel-5.9.5.ebuild, dev-qt/qtwebkit/qtwebkit-5.9.1.ebuild, dev-qt/qtwebsockets/qtwebsockets-5.11.0_rc2.ebuild, dev-qt/qtwebsockets/qtwebsockets-5.9.5.ebuild, profiles/arch/powerpc/package.use.mask, profiles/arch/powerpc/package.use.stable.mask, profiles/arch/powerpc/ppc32/package.use.mask, profiles/arch/powerpc/ppc32/package.use.stable.mask, profiles/arch/powerpc/ppc64/package.use.mask
Tested-by: ernsteiswuerfel
Bug: https://bugs.gentoo.org/655620
=> ~ppc keywording

dev-cpp/lucene++/lucene++-3.0.7-r1.ebuild
=> dev-cpp/lucene++: EAPI-6 bump

mail-filter/amavisd-new/amavisd-new-2.11.1-r1.ebuild
Closes: https://bugs.gentoo.org/671598
Package-Manager: Portage-2.3.52, Repoman-2.3.12
Signed-off-by: Craig Andrews <candrews@gentoo.org>
=> mail-filter/amavisd-new: Fix installed systemd service filename

eclass/font.eclass, media-fonts/oxygen-fonts/oxygen-fonts-5.4.3-r1.ebuild
@lovesegfault @mgorny @gentoo/fonts
=> font.eclass: Port to EAPI-7

profiles/package.mask
=> dev-libs/libappindicator:2 cleanup

media-gfx/meshlab/files/2016.12/meshlab-2016.12-qt-5.15.patch, media-gfx/meshlab/meshlab-2016.12-r4.ebuild, media-libs/qtav/files/qtav-1.12.0-qt5.15.patch, media-libs/qtav/qtav-1.12.0-r2.ebuild
=> Qt 5.15 revdep fixes (missing QPainterPath) and some more

media-libs/ilmbase/files/ilmbase-2.3.0-fix-bashisms.patch, media-libs/ilmbase/ilmbase-2.3.0.ebuild, media-libs/openexr/files/openexr-2.3.0-fix-bashisms.patch, media-libs/openexr/openexr-2.3.0.ebuild
https://bugs.gentoo.org/728222
https://bugs.gentoo.org/724092
=> media-libs/{ilmbase,openexr}: fix bashisms in configure scripts

net-dialup/cutecom/cutecom-0.51.0-r1.ebuild
Fix DESCRIPTION as well (no PN).
=> net-dialup/cutecom: EAPI-7, {desktop++,eutils--}.eclass, cmake.eclass

app-text/fbreader/fbreader-0.99.4-r5.ebuild, x11-wm/lumina/lumina-1.6.0.ebuild, x11-wm/lumina/lumina-9999.ebuild
=> Assorted EAPI-7 bumps

eclass/office-ext-r1.eclass
=> office-ext-r1.eclass: Drop EAPI-6 and openoffice-bin support

eclass/emboss-r2.eclass, sci-biology/embassy-mse/embassy-mse-3.0.0.660.ebuild, sci-biology/emboss/emboss-6.6.0-r1.ebuild
Ported two ebuilds for reference.
=> emboss-r2.eclass: Support EAPI-7

app-crypt/libsecret/libsecret-0.20.4.ebuild, dev-libs/gjs/gjs-1.68.1.ebuild, dev-libs/lockdev/lockdev-1.0.3.1.2-r3.ebuild, dev-python/dbus-python/dbus-python-1.2.16-r1.ebuild, dev-python/tappy/tappy-3.0.ebuild, gnome-base/gvfs/gvfs-1.48.1.ebuild, media-libs/libgphoto2/libgphoto2-2.5.27-r1.ebuild, net-fs/libnfs/libnfs-4.0.0.ebuild, profiles/arch/riscv/package.use.mask, sys-power/upower/upower-0.99.11.ebuild, x11-libs/libXScrnSaver/libXScrnSaver-1.2.3.ebuild, x11-libs/libXpresent/libXpresent-1.0.0-r1.ebuild, x11-libs/libxklavier/libxklavier-5.4.ebuild, xfce-base/thunar/thunar-4.17.3.ebuild, xfce-base/xfce4-appfinder/xfce4-appfinder-4.16.1.ebuild, xfce-base/xfce4-session/xfce4-session-4.16.0.ebuild, xfce-base/xfce4-settings/xfce4-settings-4.16.1.ebuild, xfce-base/xfdesktop/xfdesktop-4.16.0.ebuild, xfce-base/xfwm4/xfwm4-4.16.1.ebuild, xfce-extra/thunar-volman/thunar-volman-4.16.0.ebuild, xfce-extra/xfce4-screensaver/xfce4-screensaver-4.16.0.ebuild
=> riscv pull request for xfce4 07

dev-lang/python/python-3.11.0_beta3.ebuild
Tested with sparc64-unknown-linux-gnu.
Closes: https://bugs.gentoo.org/847910
Signed-off-by: Sam James <sam@gentoo.org>
=> dev-lang/python: use --with-build-python for cross builds for 3.11

sys-devel/clang-common/clang-common-16.0.0_pre20221205.ebuild, sys-devel/clang-runtime/clang-runtime-16.0.0_pre20221205.ebuild, sys-devel/clang/clang-16.0.0_pre20221205.ebuild, sys-devel/llvm-common/llvm-common-16.0.0_pre20221205.ebuild, sys-devel/llvm/llvm-16.0.0_pre20221205.ebuild, sys-libs/compiler-rt-sanitizers/compiler-rt-sanitizers-16.0.0_pre20221205.ebuild, sys-libs/compiler-rt/compiler-rt-16.0.0_pre20221205.ebuild, sys-libs/llvm-libunwind/llvm-libunwind-16.0.0_pre20221205.ebuild, sys-process/lsof/lsof-4.96.4.ebuild
=> keyword llvm-16 20221205 snapshot for loong

profiles/targets/desktop/make.defaults
Closes: https://bugs.gentoo.org/876637
=> profiles: desktop: Add xft to make.defaults

games-puzzle/ltris/ltris-1.0.19-r2.ebuild
Update to EAPI 8.
Closes: https://bugs.gentoo.org/682898
=> games-puzzle/ltris: Install highscore file in /var/games

app-eselect/eselect-rust/eselect-rust-20210703.ebuild, app-portage/pycargoebuild/pycargoebuild-0.10.ebuild, dev-lang/rust-bin/rust-bin-1.71.0.ebuild, dev-python/bcrypt/bcrypt-4.0.1.ebuild, dev-python/boltons/boltons-23.0.0.ebuild, dev-python/cryptography/cryptography-41.0.2.ebuild, dev-python/dirty-equals/dirty-equals-0.6.0-r2.ebuild, dev-python/paramiko/paramiko-3.2.0.ebuild, dev-python/pooch/pooch-1.7.0.ebuild, dev-python/pynacl/pynacl-1.5.0-r2.ebuild, dev-python/pyopenssl/pyopenssl-23.2.0.ebuild, dev-python/selenium/selenium-4.10.0.ebuild, dev-python/semantic-version/semantic-version-2.10.0.ebuild, dev-python/service-identity/service-identity-23.1.0.ebuild, dev-python/setuptools-rust/setuptools-rust-1.6.0.ebuild, dev-python/trio-websocket/trio-websocket-0.10.3.ebuild, dev-python/trustme/trustme-1.1.0.ebuild, dev-util/cargo-c/cargo-c-0.9.22.ebuild, dev-util/maturin/maturin-1.1.0.ebuild, dev-util/tree-sitter-cli/tree-sitter-cli-0.20.8.ebuild, gnome-base/librsvg/librsvg-2.56.2.ebuild, media-video/rav1e/rav1e-0.6.6.ebuild, media-video/rav1e/rav1e-9999.ebuild, net-libs/libnma/libnma-1.10.6-r1.ebuild, net-misc/aria2/aria2-1.36.0-r1.ebuild, profiles/arch/loong/package.use.force, profiles/arch/loong/package.use.mask, profiles/arch/loong/parent, profiles/arch/loong/use.mask, virtual/rust/rust-1.71.0.ebuild
~~Meant for testing #31241 on loong and this should definitely get rebased after that PR is merged.~~ all done
=> No more wd40 for loong

gnome-base/nautilus/nautilus-44.2.1.ebuild, gnome-base/nautilus/nautilus-45_alpha.ebuild, gui-libs/gtk/gtk-4.10.3.ebuild, gui-libs/gtk/gtk-4.10.4.ebuild, gui-libs/gtk/gtk-4.10.5.ebuild, gui-libs/gtk/gtk-4.11.4.ebuild, gui-libs/gtk/gtk-4.12.0.ebuild, x11-libs/gtk+/gtk+-3.24.37.ebuild, x11-libs/gtk+/gtk+-3.24.38.ebuild
Maybe-Bug: https://bugs.gentoo.org/898968
@thesamesam: can you check whether this fixes the failures you saw? I tried on arm64 and couldn't reproduce the failures, so this is just a guess.
=> x11-libs/gtk+: Run tests under dbus

profiles/base/package.use.mask, profiles/package.mask
Closes: https://bugs.gentoo.org/912181
=> profiles: more php:7.4 removal masks

app-arch/file-roller/file-roller-43.0.ebuild, app-cdr/brasero/brasero-3.12.3.ebuild, app-text/evince/evince-44.3.ebuild, app-text/evince/evince-45.0.ebuild, gnome-base/gnome-control-center/gnome-control-center-45.0.ebuild, gnome-base/gnome-shell/gnome-shell-45.0.ebuild, gnome-base/nautilus/nautilus-44.2.1.ebuild, gnome-base/nautilus/nautilus-45.0.ebuild, gnome-extra/gnome-calculator/gnome-calculator-44.0.ebuild, gnome-extra/gnome-calculator/gnome-calculator-45.0.2.ebuild, gnome-extra/gnome-contacts/gnome-contacts-44.0.ebuild, gnome-extra/gnome-contacts/gnome-contacts-45.0.ebuild, gnome-extra/gnome-shell-extensions/gnome-shell-extensions-45.0.ebuild, gnome-extra/nautilus-sendto/nautilus-sendto-3.8.6-r1.ebuild, gnome-extra/sushi/sushi-44.2.ebuild, gnome-extra/sushi/sushi-45.0.ebuild, gui-libs/libadwaita/libadwaita-1.4.0.ebuild, media-gfx/gnome-font-viewer/gnome-font-viewer-44.0.ebuild, media-gfx/gnome-font-viewer/gnome-font-viewer-45.0.ebuild, media-sound/easytag/easytag-2.4.3-r4.ebuild, media-sound/easytag/easytag-2.4.3-r5.ebuild, media-sound/rhythmbox/rhythmbox-3.4.7-r2.ebuild, media-sound/sound-juicer/sound-juicer-3.40.0.ebuild, profiles/package.mask, sys-apps/baobab/baobab-44.0.ebuild, sys-apps/baobab/baobab-45.0.ebuild, x11-terms/gnome-terminal/gnome-terminal-3.44.1.ebuild, x11-terms/gnome-terminal/gnome-terminal-3.48.2.ebuild, x11-wm/mutter/mutter-45.0.ebuild
=> profiles: Unmask GNOME 45.0

profiles/arch/amd64/package.use.mask, profiles/arch/base/package.use.mask, profiles/arch/hppa/package.use.mask, profiles/arch/loong/package.use.mask, profiles/arch/powerpc/ppc64/64le/package.use.mask, profiles/arch/sparc/package.use.mask, profiles/arch/x86/package.use.mask
See also: https://github.com/gentoo/qt/pull/271
=> profiles: Cleanup outdated IUSE vulkan package.use.mask entries

dev-lisp/cl-ppcre-unicode/cl-ppcre-unicode-2.1.0-r1.ebuild, dev-lisp/cl-ppcre/cl-ppcre-2.1.0-r1.ebuild, dev-lisp/cl-unicode/cl-unicode-0.1.5-r1.ebuild, dev-lisp/clx/clx-0.7.5-r1.ebuild, dev-lisp/trivial-gray-streams/trivial-gray-streams-20170830-r1.ebuild
=> dev-lisp/*: Update some packages to EAPI 7

sys-libs/glibc/glibc-2.19-r3.ebuild, sys-libs/glibc/glibc-2.31-r7.ebuild, sys-libs/glibc/glibc-2.32-r8.ebuild, sys-libs/glibc/glibc-2.33-r14.ebuild, sys-libs/glibc/glibc-2.34-r14.ebuild, sys-libs/glibc/glibc-2.35-r11.ebuild, sys-libs/glibc/glibc-2.36-r8.ebuild, sys-libs/glibc/glibc-2.37-r10.ebuild, sys-libs/glibc/glibc-2.38-r13.ebuild, sys-libs/glibc/glibc-2.39-r6.ebuild, sys-libs/glibc/glibc-2.39-r7.ebuild, sys-libs/glibc/glibc-2.39-r9.ebuild, sys-libs/glibc/glibc-9999.ebuild
Closes: https://bugs.gentoo.org/934391
=> sys-libs/glibc: improve amd64 multilib message

eclass/kernel-2.eclass, eclass/linux-info.eclass
=> linux-info.eclass: Drop support for EAPI 6, drop temporary fix for powerpc

eclass/kernel-build.eclass
genpatches will soon be adding optional CTF debug information support via a patch. If it's enabled, we need to call a few special make targets to create and install the CTF information. We also need to avoid stripping the CTF archive.
=> kernel-build.eclass: handle CTF if enabled

kde-plasma/kwin/kwin-6.2.2-r1.ebuild
Closes: https://bugs.gentoo.org/941628
=> kde-plasma/kwin: set cap_sys_nice=ep on kwin_wayland

dev-gap/metadata.xml
=> dev-gap: Add German translation to category metadata

media-libs/libyuv/files/0002-disable-static-library.patch, media-libs/libyuv/libyuv-1904.ebuild, media-libs/libyuv/libyuv-9999.ebuild
Bug: https://bugs.gentoo.org/952112
[build.log](https://github.com/user-attachments/files/19475800/build.log)
=> media-libs/libyuv: Enable tests

dev-libs/openssl/openssl-3.0.16.ebuild, dev-libs/openssl/openssl-3.0.17.ebuild, dev-libs/openssl/openssl-3.0.9999.ebuild, dev-libs/openssl/openssl-3.1.8.ebuild, dev-libs/openssl/openssl-3.1.9999.ebuild, dev-libs/openssl/openssl-3.2.4.ebuild, dev-libs/openssl/openssl-3.2.5.ebuild, dev-libs/openssl/openssl-3.2.9999.ebuild, dev-libs/openssl/openssl-3.3.3.ebuild, dev-libs/openssl/openssl-3.3.4.ebuild, dev-libs/openssl/openssl-3.3.9999.ebuild, dev-libs/openssl/openssl-3.4.1.ebuild, dev-libs/openssl/openssl-3.4.2.ebuild, dev-libs/openssl/openssl-3.4.9999.ebuild, dev-libs/openssl/openssl-3.5.0.ebuild, dev-libs/openssl/openssl-3.5.1.ebuild, dev-libs/openssl/openssl-3.5.9999.ebuild
Closes: https://bugs.gentoo.org/960478
=> dev-libs/openssl: set LD_LIBRARY_PATH when calling openssl
